// GENERATED by tools/gen-roster.ts — do not edit by hand (curate a line in roster.ts instead).
// 196 lines.
import type { RosterLine } from './roster';

export const GENERATED: RosterLine[] = [
 {
  "id": "caterpie",
  "role": "Balanced",
  "blurb": "The Butterfly Pokémon. Ability: Compound Eyes.",
  "level": 61,
  "evoRate": 2.5,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "CATERPIE",
    "moves": [
     "TACKLE"
    ]
   },
   {
    "species": "METAPOD",
    "moves": [
     "TACKLE",
     "HARDEN"
    ]
   },
   {
    "species": "BUTTERFREE",
    "moves": [
     "SILVER_WIND",
     "AERIAL_ACE",
     "SOLAR_BEAM",
     "SLEEP_POWDER"
    ]
   }
  ]
 },
 {
  "id": "weedle",
  "role": "Balanced",
  "blurb": "The Poison Bee Pokémon. Ability: Swarm.",
  "level": 61,
  "evoRate": 2.5,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "WEEDLE",
    "moves": [
     "POISON_STING"
    ]
   },
   {
    "species": "KAKUNA",
    "moves": [
     "POISON_STING",
     "HARDEN"
    ]
   },
   {
    "species": "BEEDRILL",
    "moves": [
     "TWINEEDLE",
     "SLUDGE_BOMB",
     "BRICK_BREAK",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "rattata",
  "role": "Balanced",
  "blurb": "The Mouse Pokémon. Ability: Run Away.",
  "level": 56,
  "evoRate": 1.5,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "RATTATA",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "THUNDER_WAVE",
     "HYPER_FANG"
    ]
   },
   {
    "species": "RATICATE",
    "moves": [
     "DOUBLE_EDGE",
     "SHADOW_BALL",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "spearow",
  "role": "Physical Sweeper",
  "blurb": "The Beak Pokémon. Ability: Keen Eye.",
  "level": 53,
  "evoRate": 1.5,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "SPEAROW",
    "moves": [
     "TRI_ATTACK",
     "DRILL_PECK",
     "STEEL_WING",
     "AGILITY"
    ]
   },
   {
    "species": "FEAROW",
    "moves": [
     "DOUBLE_EDGE",
     "SKY_ATTACK",
     "STEEL_WING",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "ekans",
  "role": "Balanced",
  "blurb": "The Cobra Pokémon. Ability: Intimidate.",
  "level": 54,
  "evoRate": 1.36,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "EKANS",
    "moves": [
     "SLUDGE_BOMB",
     "ROCK_SLIDE",
     "GLARE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "ARBOK",
    "moves": [
     "SLUDGE_BOMB",
     "EARTHQUAKE",
     "GLARE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "sandshrew",
  "role": "Balanced",
  "blurb": "The Mouse Pokémon. Ability: Sand Veil.",
  "level": 53,
  "evoRate": 1.36,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "SANDSHREW",
    "moves": [
     "DIG",
     "BRICK_BREAK",
     "SWORDS_DANCE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "SANDSLASH",
    "moves": [
     "EARTHQUAKE",
     "BRICK_BREAK",
     "SWORDS_DANCE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "nidoran-f",
  "role": "Bruiser",
  "blurb": "The Drill Pokémon. Ability: Poison Point.",
  "level": 52,
  "evoRate": 1.88,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "NIDORAN_F",
    "moves": [
     "POISON_STING",
     "DOUBLE_KICK",
     "AERIAL_ACE",
     "BITE"
    ]
   },
   {
    "species": "NIDORINA",
    "moves": [
     "SLUDGE_BOMB",
     "ICE_BEAM",
     "BODY_SLAM",
     "THUNDERBOLT"
    ]
   },
   {
    "species": "NIDOQUEEN",
    "moves": [
     "SLUDGE_BOMB",
     "EARTHQUAKE",
     "SUPERPOWER",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "vulpix",
  "role": "Speedster",
  "blurb": "The Fox Pokémon. Ability: Flash Fire.",
  "level": 48,
  "evoRate": 1.1,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "VULPIX",
    "moves": [
     "EMBER",
     "FAINT_ATTACK",
     "CONFUSE_RAY",
     "BODY_SLAM"
    ]
   },
   {
    "species": "NINETALES",
    "moves": [
     "OVERHEAT",
     "DOUBLE_EDGE",
     "REST",
     "FIRE_BLAST"
    ]
   }
  ]
 },
 {
  "id": "zubat",
  "role": "Physical Sweeper",
  "blurb": "The Bat Pokémon. Ability: Inner Focus.",
  "level": 49,
  "evoRate": 1.36,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "ZUBAT",
    "moves": [
     "POISON_FANG",
     "WING_ATTACK",
     "STEEL_WING",
     "CONFUSE_RAY"
    ]
   },
   {
    "species": "GOLBAT",
    "moves": [
     "SLUDGE_BOMB",
     "WING_ATTACK",
     "SHADOW_BALL",
     "CONFUSE_RAY"
    ]
   },
   {
    "species": "CROBAT",
    "moves": [
     "SLUDGE_BOMB",
     "WING_ATTACK",
     "SHADOW_BALL",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "oddish-bellossom",
  "role": "Bruiser",
  "blurb": "The Flower Pokémon. Ability: Chlorophyll.",
  "level": 53,
  "evoRate": 1.43,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "ODDISH",
    "moves": [
     "PETAL_DANCE",
     "ACID",
     "FLAIL",
     "SLEEP_POWDER"
    ]
   },
   {
    "species": "GLOOM",
    "moves": [
     "PETAL_DANCE",
     "SLUDGE_BOMB",
     "FLAIL",
     "SLEEP_POWDER"
    ]
   },
   {
    "species": "BELLOSSOM",
    "moves": [
     "SOLAR_BEAM",
     "SLUDGE_BOMB",
     "MOONLIGHT",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "paras",
  "role": "Balanced",
  "blurb": "The Mushroom Pokémon. Ability: Effect Spore.",
  "level": 56,
  "evoRate": 1.25,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "PARAS",
    "moves": [
     "LEECH_LIFE",
     "GIGA_DRAIN",
     "SLUDGE_BOMB",
     "SPORE"
    ]
   },
   {
    "species": "PARASECT",
    "moves": [
     "LEECH_LIFE",
     "SOLAR_BEAM",
     "DOUBLE_EDGE",
     "SPORE"
    ]
   }
  ]
 },
 {
  "id": "venonat",
  "role": "Balanced",
  "blurb": "The Poison Moth Pokémon. Ability: Shield Dust.",
  "level": 53,
  "evoRate": 0.97,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "VENONAT",
    "moves": [
     "SIGNAL_BEAM",
     "SLUDGE_BOMB",
     "PSYCHIC",
     "SLEEP_POWDER"
    ]
   },
   {
    "species": "VENOMOTH",
    "moves": [
     "SIGNAL_BEAM",
     "SLUDGE_BOMB",
     "PSYCHIC",
     "SLEEP_POWDER"
    ]
   }
  ]
 },
 {
  "id": "diglett",
  "role": "Speedster",
  "blurb": "The Mole Pokémon. Ability: Sand Veil.",
  "level": 56,
  "evoRate": 1.15,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "DIGLETT",
    "moves": [
     "MAGNITUDE",
     "SLUDGE_BOMB",
     "BODY_SLAM",
     "ROCK_SLIDE"
    ]
   },
   {
    "species": "DUGTRIO",
    "moves": [
     "EARTHQUAKE",
     "SLUDGE_BOMB",
     "DOUBLE_EDGE",
     "ROCK_SLIDE"
    ]
   }
  ]
 },
 {
  "id": "meowth",
  "role": "Speedster",
  "blurb": "The Classy Cat Pokémon. Ability: Limber.",
  "level": 53,
  "evoRate": 1.07,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "MEOWTH",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "HYPNOSIS",
     "SLASH"
    ]
   },
   {
    "species": "PERSIAN",
    "moves": [
     "DOUBLE_EDGE",
     "THUNDERBOLT",
     "HYPNOSIS",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "psyduck",
  "role": "Balanced",
  "blurb": "The Duck Pokémon. Ability: Damp.",
  "level": 48,
  "evoRate": 0.91,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "PSYDUCK",
    "moves": [
     "WATERFALL",
     "PSYCHIC",
     "CALM_MIND",
     "WATER_PULSE"
    ]
   },
   {
    "species": "GOLDUCK",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "CALM_MIND",
     "SURF"
    ]
   }
  ]
 },
 {
  "id": "mankey",
  "role": "Balanced",
  "blurb": "The Pig Monkey Pokémon. Ability: Vital Spirit.",
  "level": 52,
  "evoRate": 1.07,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "MANKEY",
    "moves": [
     "BRICK_BREAK",
     "ROCK_SLIDE",
     "BULK_UP",
     "THRASH"
    ]
   },
   {
    "species": "PRIMEAPE",
    "moves": [
     "CROSS_CHOP",
     "EARTHQUAKE",
     "BULK_UP",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "growlithe",
  "role": "Heavy Hitter",
  "blurb": "The Legendary Pokémon. Ability: Intimidate.",
  "level": 44,
  "evoRate": 1.1,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "GROWLITHE",
    "moves": [
     "FLAME_WHEEL",
     "CRUNCH",
     "AGILITY",
     "THRASH"
    ]
   },
   {
    "species": "ARCANINE",
    "moves": [
     "OVERHEAT",
     "DOUBLE_EDGE",
     "AGILITY",
     "FIRE_BLAST"
    ]
   }
  ]
 },
 {
  "id": "poliwag-politoed",
  "role": "Bruiser",
  "blurb": "The Frog Pokémon. Ability: Water Absorb.",
  "level": 52,
  "evoRate": 1.2,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "POLIWAG",
    "moves": [
     "BUBBLE_BEAM",
     "DIG",
     "BELLY_DRUM",
     "WATER_PULSE"
    ]
   },
   {
    "species": "POLIWHIRL",
    "moves": [
     "SURF",
     "BRICK_BREAK",
     "BELLY_DRUM",
     "BODY_SLAM"
    ]
   },
   {
    "species": "POLITOED",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "REST",
     "SURF"
    ]
   }
  ]
 },
 {
  "id": "bellsprout",
  "role": "Balanced",
  "blurb": "The Flycatcher Pokémon. Ability: Chlorophyll.",
  "level": 53,
  "evoRate": 1.43,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "BELLSPROUT",
    "moves": [
     "GIGA_DRAIN",
     "ACID",
     "CUT",
     "SWORDS_DANCE"
    ]
   },
   {
    "species": "WEEPINBELL",
    "moves": [
     "GIGA_DRAIN",
     "SLUDGE_BOMB",
     "SLAM",
     "SWORDS_DANCE"
    ]
   },
   {
    "species": "VICTREEBEL",
    "moves": [
     "SOLAR_BEAM",
     "SLUDGE_BOMB",
     "DOUBLE_EDGE",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "tentacool",
  "role": "Speedster",
  "blurb": "The Jellyfish Pokémon. Ability: Clear Body.",
  "level": 47,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "TENTACOOL",
    "moves": [
     "WATERFALL",
     "SLUDGE_BOMB",
     "AURORA_BEAM",
     "CONFUSE_RAY"
    ]
   },
   {
    "species": "TENTACRUEL",
    "moves": [
     "HYDRO_PUMP",
     "SLUDGE_BOMB",
     "ICE_BEAM",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "ponyta",
  "role": "Physical Sweeper",
  "blurb": "The Fire Horse Pokémon. Ability: Run Away.",
  "level": 48,
  "evoRate": 0.8,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "PONYTA",
    "moves": [
     "FLAME_WHEEL",
     "THRASH",
     "AGILITY",
     "BODY_SLAM"
    ]
   },
   {
    "species": "RAPIDASH",
    "moves": [
     "OVERHEAT",
     "DOUBLE_EDGE",
     "AGILITY",
     "FIRE_BLAST"
    ]
   }
  ]
 },
 {
  "id": "slowpoke-slowbro",
  "role": "Bruiser",
  "blurb": "The Hermit Crab Pokémon. Ability: Oblivious.",
  "level": 49,
  "evoRate": 0.81,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "SLOWPOKE",
    "moves": [
     "WATER_PULSE",
     "PSYCHIC",
     "SHADOW_BALL",
     "THUNDER_WAVE"
    ]
   },
   {
    "species": "SLOWBRO",
    "moves": [
     "SURF",
     "PSYCHIC",
     "FIRE_BLAST",
     "CALM_MIND"
    ]
   }
  ]
 },
 {
  "id": "slowpoke-slowking",
  "role": "Bruiser",
  "blurb": "The Royal Pokémon. Ability: Oblivious.",
  "level": 49,
  "evoRate": 1.1,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "SLOWPOKE",
    "moves": [
     "WATER_PULSE",
     "PSYCHIC",
     "SHADOW_BALL",
     "THUNDER_WAVE"
    ]
   },
   {
    "species": "SLOWKING",
    "moves": [
     "SURF",
     "PSYCHIC",
     "FIRE_BLAST",
     "CALM_MIND"
    ]
   }
  ]
 },
 {
  "id": "magnemite",
  "role": "Special Nuker",
  "blurb": "The Magnet Pokémon. Ability: Magnet Pull.",
  "level": 51,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "MAGNEMITE",
    "moves": [
     "SPARK",
     "SWIFT",
     "THUNDER_WAVE",
     "SHOCK_WAVE"
    ]
   },
   {
    "species": "MAGNETON",
    "moves": [
     "THUNDERBOLT",
     "DOUBLE_EDGE",
     "THUNDER_WAVE",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "farfetchd",
  "role": "Balanced",
  "blurb": "The Wild Duck Pokémon. Ability: Keen Eye.",
  "level": 60,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "FARFETCHD",
    "moves": [
     "DOUBLE_EDGE",
     "AERIAL_ACE",
     "IRON_TAIL",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "doduo",
  "role": "Physical Sweeper",
  "blurb": "The Triple Bird Pokémon. Ability: Run Away.",
  "level": 52,
  "evoRate": 0.97,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "DODUO",
    "moves": [
     "BODY_SLAM",
     "DRILL_PECK",
     "STEEL_WING",
     "AGILITY"
    ]
   },
   {
    "species": "DODRIO",
    "moves": [
     "DOUBLE_EDGE",
     "DRILL_PECK",
     "STEEL_WING",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "grimer",
  "role": "Bruiser",
  "blurb": "The Sludge Pokémon. Ability: Stench.",
  "level": 48,
  "evoRate": 0.8,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "GRIMER",
    "moves": [
     "SLUDGE_BOMB",
     "BODY_SLAM",
     "ACID_ARMOR",
     "SLUDGE"
    ]
   },
   {
    "species": "MUK",
    "moves": [
     "SLUDGE_BOMB",
     "BRICK_BREAK",
     "REST",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "shellder",
  "role": "Bruiser",
  "blurb": "The Bivalve Pokémon. Ability: Shell Armor.",
  "level": 46,
  "evoRate": 1.1,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "SHELLDER",
    "moves": [
     "BUBBLE_BEAM",
     "TAKE_DOWN",
     "AURORA_BEAM",
     "TACKLE"
    ]
   },
   {
    "species": "CLOYSTER",
    "moves": [
     "SURF",
     "ICE_BEAM",
     "DOUBLE_EDGE",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "drowzee",
  "role": "Bruiser",
  "blurb": "The Hypnosis Pokémon. Ability: Insomnia.",
  "level": 50,
  "evoRate": 1.15,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "DROWZEE",
    "moves": [
     "PSYCHIC",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "HYPNO",
    "moves": [
     "PSYCHIC",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "krabby",
  "role": "Heavy Hitter",
  "blurb": "The Pincer Pokémon. Ability: Hyper Cutter.",
  "level": 50,
  "evoRate": 1.07,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "KRABBY",
    "moves": [
     "CRABHAMMER",
     "BODY_SLAM",
     "SWORDS_DANCE",
     "MUD_SHOT"
    ]
   },
   {
    "species": "KINGLER",
    "moves": [
     "SURF",
     "DOUBLE_EDGE",
     "SWORDS_DANCE",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "voltorb",
  "role": "Speedster",
  "blurb": "The Ball Pokémon. Ability: Soundproof.",
  "level": 50,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "VOLTORB",
    "moves": [
     "SPARK",
     "MIRROR_COAT",
     "THUNDER_WAVE",
     "SHOCK_WAVE"
    ]
   },
   {
    "species": "ELECTRODE",
    "moves": [
     "THUNDERBOLT",
     "EXPLOSION",
     "THUNDER_WAVE",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "exeggcute",
  "role": "Special Nuker",
  "blurb": "The Coconut Pokémon. Ability: Chlorophyll.",
  "level": 47,
  "evoRate": 1.1,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "EXEGGCUTE",
    "moves": [
     "GIGA_DRAIN",
     "PSYCHIC",
     "SLUDGE_BOMB",
     "SLEEP_POWDER"
    ]
   },
   {
    "species": "EXEGGUTOR",
    "moves": [
     "SOLAR_BEAM",
     "PSYCHIC",
     "SLUDGE_BOMB",
     "MOONLIGHT"
    ]
   }
  ]
 },
 {
  "id": "cubone",
  "role": "Balanced",
  "blurb": "The Bone Keeper Pokémon. Ability: Rock Head.",
  "level": 55,
  "evoRate": 1.07,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "CUBONE",
    "moves": [
     "BONEMERANG",
     "BRICK_BREAK",
     "SWORDS_DANCE",
     "THRASH"
    ]
   },
   {
    "species": "MAROWAK",
    "moves": [
     "EARTHQUAKE",
     "DOUBLE_EDGE",
     "SWORDS_DANCE",
     "BONEMERANG"
    ]
   }
  ]
 },
 {
  "id": "lickitung",
  "role": "Balanced",
  "blurb": "The Licking Pokémon. Ability: Own Tempo.",
  "level": 57,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "LICKITUNG",
    "moves": [
     "DOUBLE_EDGE",
     "FIRE_BLAST",
     "ICE_BEAM",
     "THUNDERBOLT"
    ]
   }
  ]
 },
 {
  "id": "koffing",
  "role": "Bruiser",
  "blurb": "The Poison Gas Pokémon. Ability: Levitate.",
  "level": 49,
  "evoRate": 0.86,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "KOFFING",
    "moves": [
     "SLUDGE_BOMB",
     "SHADOW_BALL",
     "WILL_O_WISP",
     "SLUDGE"
    ]
   },
   {
    "species": "WEEZING",
    "moves": [
     "SLUDGE_BOMB",
     "FIRE_BLAST",
     "REST",
     "EXPLOSION"
    ]
   }
  ]
 },
 {
  "id": "rhyhorn",
  "role": "Heavy Hitter",
  "blurb": "The Drill Pokémon. Ability: Lightning Rod.",
  "level": 50,
  "evoRate": 0.8,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "RHYHORN",
    "moves": [
     "MAGNITUDE",
     "ROCK_SLIDE",
     "BODY_SLAM",
     "SWORDS_DANCE"
    ]
   },
   {
    "species": "RHYDON",
    "moves": [
     "EARTHQUAKE",
     "ROCK_SLIDE",
     "MEGAHORN",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "chansey",
  "role": "Tank",
  "blurb": "The Happiness Pokémon. Ability: Natural Cure.",
  "level": 45,
  "evoRate": 1.1,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "CHANSEY",
    "moves": [
     "BODY_SLAM",
     "PSYCHIC",
     "SOFT_BOILED",
     "WATER_PULSE"
    ]
   },
   {
    "species": "BLISSEY",
    "moves": [
     "DOUBLE_EDGE",
     "FIRE_BLAST",
     "SOFT_BOILED",
     "ICE_BEAM"
    ]
   }
  ]
 },
 {
  "id": "tangela",
  "role": "Balanced",
  "blurb": "The Vine Pokémon. Ability: Chlorophyll.",
  "level": 53,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "TANGELA",
    "moves": [
     "SOLAR_BEAM",
     "CONFUSION",
     "SLEEP_POWDER",
     "GIGA_DRAIN"
    ]
   }
  ]
 },
 {
  "id": "kangaskhan",
  "role": "Bruiser",
  "blurb": "The Parent Pokémon. Ability: Early Bird.",
  "level": 48,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "KANGASKHAN",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "REST",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "horsea",
  "role": "Bruiser",
  "blurb": "The Dragon Pokémon. Ability: Swift Swim.",
  "level": 48,
  "evoRate": 0.94,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "HORSEA",
    "moves": [
     "WATER_PULSE",
     "AURORA_BEAM",
     "AGILITY",
     "DRAGON_BREATH"
    ]
   },
   {
    "species": "SEADRA",
    "moves": [
     "SURF",
     "ICE_BEAM",
     "AGILITY",
     "WATERFALL"
    ]
   },
   {
    "species": "KINGDRA",
    "moves": [
     "HYDRO_PUMP",
     "DRAGON_BREATH",
     "ICE_BEAM",
     "DRAGON_DANCE"
    ]
   }
  ]
 },
 {
  "id": "goldeen",
  "role": "Balanced",
  "blurb": "The Goldfish Pokémon. Ability: Swift Swim.",
  "level": 53,
  "evoRate": 0.91,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "GOLDEEN",
    "moves": [
     "WATERFALL",
     "HORN_ATTACK",
     "AGILITY",
     "FLAIL"
    ]
   },
   {
    "species": "SEAKING",
    "moves": [
     "HYDRO_PUMP",
     "MEGAHORN",
     "AGILITY",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "staryu",
  "role": "Special Sweeper",
  "blurb": "The Mysterious Pokémon. Ability: Illuminate.",
  "level": 47,
  "evoRate": 1.1,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "STARYU",
    "moves": [
     "WATERFALL",
     "PSYCHIC",
     "THUNDER_WAVE",
     "BUBBLE_BEAM"
    ]
   },
   {
    "species": "STARMIE",
    "moves": [
     "HYDRO_PUMP",
     "PSYCHIC",
     "ICE_BEAM",
     "THUNDER_WAVE"
    ]
   }
  ]
 },
 {
  "id": "mr-mime",
  "role": "Balanced",
  "blurb": "The Barrier Pokémon. Ability: Soundproof.",
  "level": 51,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "MR_MIME",
    "moves": [
     "PSYCHIC",
     "THUNDERBOLT",
     "CALM_MIND",
     "SOLAR_BEAM"
    ]
   }
  ]
 },
 {
  "id": "pinsir",
  "role": "Heavy Hitter",
  "blurb": "The Stag Beetle Pokémon. Ability: Hyper Cutter.",
  "level": 48,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "PINSIR",
    "moves": [
     "EARTHQUAKE",
     "SWORDS_DANCE",
     "DOUBLE_EDGE",
     "REVENGE"
    ]
   }
  ]
 },
 {
  "id": "tauros",
  "role": "Physical Sweeper",
  "blurb": "The Wild Bull Pokémon. Ability: Intimidate.",
  "level": 48,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "TAUROS",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "THRASH",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "lapras",
  "role": "Tank",
  "blurb": "The Transport Pokémon. Ability: Water Absorb.",
  "level": 45,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "LAPRAS",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "PSYCHIC",
     "DRAGON_DANCE"
    ]
   }
  ]
 },
 {
  "id": "ditto",
  "role": "Balanced",
  "blurb": "The Transform Pokémon. Ability: Limber.",
  "level": 65,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "DITTO",
    "moves": [
     "TRANSFORM"
    ]
   }
  ]
 },
 {
  "id": "eevee-jolteon",
  "role": "Special Sweeper",
  "blurb": "The Lightning Pokémon. Ability: Volt Absorb.",
  "level": 46,
  "evoRate": 1.1,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "EEVEE",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "WISH",
     "TAKE_DOWN"
    ]
   },
   {
    "species": "JOLTEON",
    "moves": [
     "THUNDERBOLT",
     "BITE",
     "THUNDER_WAVE",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "eevee-vaporeon",
  "role": "Special Nuker",
  "blurb": "The Bubble Jet Pokémon. Ability: Water Absorb.",
  "level": 46,
  "evoRate": 1.1,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "EEVEE",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "WISH",
     "TAKE_DOWN"
    ]
   },
   {
    "species": "VAPOREON",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "WISH",
     "SURF"
    ]
   }
  ]
 },
 {
  "id": "eevee-flareon",
  "role": "Heavy Hitter",
  "blurb": "The Flame Pokémon. Ability: Flash Fire.",
  "level": 46,
  "evoRate": 1.1,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "EEVEE",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "WISH",
     "TAKE_DOWN"
    ]
   },
   {
    "species": "FLAREON",
    "moves": [
     "OVERHEAT",
     "SHADOW_BALL",
     "WISH",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "eevee-espeon",
  "role": "Special Sweeper",
  "blurb": "The Sun Pokémon. Ability: Synchronize.",
  "level": 46,
  "evoRate": 1.1,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "EEVEE",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "WISH",
     "TAKE_DOWN"
    ]
   },
   {
    "species": "ESPEON",
    "moves": [
     "PSYCHIC",
     "BITE",
     "CALM_MIND",
     "PSYBEAM"
    ]
   }
  ]
 },
 {
  "id": "eevee-umbreon",
  "role": "Tank",
  "blurb": "The Moonlight Pokémon. Ability: Synchronize.",
  "level": 46,
  "evoRate": 1.1,
  "tags": [
   "kanto",
   "branch"
  ],
  "stages": [
   {
    "species": "EEVEE",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "WISH",
     "TAKE_DOWN"
    ]
   },
   {
    "species": "UMBREON",
    "moves": [
     "BITE",
     "PSYCHIC",
     "MOONLIGHT",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "porygon",
  "role": "Bruiser",
  "blurb": "The Virtual Pokémon. Ability: Trace.",
  "level": 47,
  "evoRate": 1.1,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "PORYGON",
    "moves": [
     "TRI_ATTACK",
     "PSYCHIC",
     "THUNDER_WAVE",
     "SHOCK_WAVE"
    ]
   },
   {
    "species": "PORYGON2",
    "moves": [
     "DOUBLE_EDGE",
     "ICE_BEAM",
     "RECOVER",
     "THUNDERBOLT"
    ]
   }
  ]
 },
 {
  "id": "omanyte",
  "role": "Special Nuker",
  "blurb": "The Spiral Pokémon. Ability: Swift Swim.",
  "level": 49,
  "evoRate": 0.8,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "OMANYTE",
    "moves": [
     "ROCK_SLIDE",
     "WATERFALL",
     "AURORA_BEAM",
     "BUBBLE_BEAM"
    ]
   },
   {
    "species": "OMASTAR",
    "moves": [
     "ROCK_SLIDE",
     "HYDRO_PUMP",
     "ICE_BEAM",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "kabuto",
  "role": "Heavy Hitter",
  "blurb": "The Shellfish Pokémon. Ability: Swift Swim.",
  "level": 49,
  "evoRate": 0.8,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "KABUTO",
    "moves": [
     "ROCK_SLIDE",
     "WATERFALL",
     "BODY_SLAM",
     "CONFUSE_RAY"
    ]
   },
   {
    "species": "KABUTOPS",
    "moves": [
     "ROCK_SLIDE",
     "SURF",
     "BRICK_BREAK",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "aerodactyl",
  "role": "Physical Sweeper",
  "blurb": "The Fossil Pokémon. Ability: Rock Head.",
  "level": 46,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "AERODACTYL",
    "moves": [
     "ROCK_SLIDE",
     "WING_ATTACK",
     "EARTHQUAKE",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "snorlax",
  "role": "Heavy Hitter",
  "blurb": "The Sleeping Pokémon. Ability: Immunity.",
  "level": 44,
  "tags": [
   "kanto"
  ],
  "stages": [
   {
    "species": "SNORLAX",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "BELLY_DRUM",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "articuno",
  "role": "Legendary",
  "blurb": "The Freeze Pokémon. Ability: Pressure.",
  "level": 41,
  "tags": [
   "kanto",
   "legendary"
  ],
  "stages": [
   {
    "species": "ARTICUNO",
    "moves": [
     "ICE_BEAM",
     "AERIAL_ACE",
     "DOUBLE_EDGE",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "zapdos",
  "role": "Legendary",
  "blurb": "The Electric Pokémon. Ability: Pressure.",
  "level": 41,
  "tags": [
   "kanto",
   "legendary"
  ],
  "stages": [
   {
    "species": "ZAPDOS",
    "moves": [
     "THUNDERBOLT",
     "DRILL_PECK",
     "DOUBLE_EDGE",
     "THUNDER_WAVE"
    ]
   }
  ]
 },
 {
  "id": "moltres",
  "role": "Legendary",
  "blurb": "The Flame Pokémon. Ability: Pressure.",
  "level": 41,
  "tags": [
   "kanto",
   "legendary"
  ],
  "stages": [
   {
    "species": "MOLTRES",
    "moves": [
     "OVERHEAT",
     "SKY_ATTACK",
     "DOUBLE_EDGE",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "mewtwo",
  "role": "Legendary",
  "blurb": "The Genetic Pokémon. Ability: Pressure.",
  "level": 33,
  "tags": [
   "kanto",
   "legendary"
  ],
  "stages": [
   {
    "species": "MEWTWO",
    "moves": [
     "PSYCHIC",
     "FIRE_BLAST",
     "RECOVER",
     "ICE_BEAM"
    ]
   }
  ]
 },
 {
  "id": "mew",
  "role": "Legendary",
  "blurb": "The New Species Pokémon. Ability: Synchronize.",
  "level": 39,
  "tags": [
   "kanto",
   "legendary"
  ],
  "stages": [
   {
    "species": "MEW",
    "moves": [
     "PSYCHIC",
     "OVERHEAT",
     "TRANSFORM",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "chikorita",
  "role": "Bruiser",
  "blurb": "The Herb Pokémon. Ability: Overgrow.",
  "level": 50,
  "evoRate": 1.88,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "CHIKORITA",
    "moves": [
     "GIGA_DRAIN",
     "ANCIENT_POWER",
     "SWORDS_DANCE",
     "FLAIL"
    ]
   },
   {
    "species": "BAYLEEF",
    "moves": [
     "GIGA_DRAIN",
     "ANCIENT_POWER",
     "SYNTHESIS",
     "BODY_SLAM"
    ]
   },
   {
    "species": "MEGANIUM",
    "moves": [
     "SOLAR_BEAM",
     "EARTHQUAKE",
     "SYNTHESIS",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "cyndaquil",
  "role": "Special Sweeper",
  "blurb": "The Volcano Pokémon. Ability: Blaze.",
  "level": 49,
  "evoRate": 2.14,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "CYNDAQUIL",
    "moves": [
     "FLAME_WHEEL",
     "REVERSAL",
     "SWIFT",
     "AERIAL_ACE"
    ]
   },
   {
    "species": "QUILAVA",
    "moves": [
     "FLAMETHROWER",
     "BRICK_BREAK",
     "FLAME_WHEEL",
     "THRASH"
    ]
   },
   {
    "species": "TYPHLOSION",
    "moves": [
     "OVERHEAT",
     "EARTHQUAKE",
     "REST",
     "FLAMETHROWER"
    ]
   }
  ]
 },
 {
  "id": "totodile",
  "role": "Bruiser",
  "blurb": "The Big Jaw Pokémon. Ability: Torrent.",
  "level": 49,
  "evoRate": 1.67,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "TOTODILE",
    "moves": [
     "WATER_PULSE",
     "SEISMIC_TOSS",
     "SWORDS_DANCE",
     "SLASH"
    ]
   },
   {
    "species": "CROCONAW",
    "moves": [
     "SURF",
     "BRICK_BREAK",
     "SWORDS_DANCE",
     "THRASH"
    ]
   },
   {
    "species": "FERALIGATR",
    "moves": [
     "HYDRO_PUMP",
     "EARTHQUAKE",
     "SWORDS_DANCE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "sentret",
  "role": "Balanced",
  "blurb": "The Long Body Pokémon. Ability: Run Away.",
  "level": 55,
  "evoRate": 2,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SENTRET",
    "moves": [
     "BODY_SLAM",
     "BRICK_BREAK",
     "AMNESIA",
     "SHADOW_BALL"
    ]
   },
   {
    "species": "FURRET",
    "moves": [
     "DOUBLE_EDGE",
     "BRICK_BREAK",
     "AMNESIA",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "hoothoot",
  "role": "Balanced",
  "blurb": "The Owl Pokémon. Ability: Insomnia.",
  "level": 53,
  "evoRate": 1.5,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "HOOTHOOT",
    "moves": [
     "TAKE_DOWN",
     "AERIAL_ACE",
     "PSYCHIC",
     "HYPNOSIS"
    ]
   },
   {
    "species": "NOCTOWL",
    "moves": [
     "DOUBLE_EDGE",
     "SKY_ATTACK",
     "PSYCHIC",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "ledyba",
  "role": "Balanced",
  "blurb": "The Five Star Pokémon. Ability: Swarm.",
  "level": 58,
  "evoRate": 1.67,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "LEDYBA",
    "moves": [
     "SILVER_WIND",
     "AERIAL_ACE",
     "GIGA_DRAIN",
     "AGILITY"
    ]
   },
   {
    "species": "LEDIAN",
    "moves": [
     "SILVER_WIND",
     "AERIAL_ACE",
     "SOLAR_BEAM",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "spinarak",
  "role": "Balanced",
  "blurb": "The Long Leg Pokémon. Ability: Swarm.",
  "level": 58,
  "evoRate": 1.36,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SPINARAK",
    "moves": [
     "SIGNAL_BEAM",
     "SLUDGE_BOMB",
     "BODY_SLAM",
     "AGILITY"
    ]
   },
   {
    "species": "ARIADOS",
    "moves": [
     "SIGNAL_BEAM",
     "SLUDGE_BOMB",
     "DOUBLE_EDGE",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "chinchou",
  "role": "Bruiser",
  "blurb": "The Light Pokémon. Ability: Volt Absorb.",
  "level": 52,
  "evoRate": 1.11,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "CHINCHOU",
    "moves": [
     "WATERFALL",
     "SPARK",
     "TAKE_DOWN",
     "THUNDER_WAVE"
    ]
   },
   {
    "species": "LANTURN",
    "moves": [
     "HYDRO_PUMP",
     "THUNDERBOLT",
     "ICE_BEAM",
     "THUNDER_WAVE"
    ]
   }
  ]
 },
 {
  "id": "pichu",
  "role": "Physical Sweeper",
  "blurb": "The Mouse Pokémon. Ability: Static.",
  "level": 54,
  "evoRate": 1.1,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "PICHU",
    "moves": [
     "SHOCK_WAVE",
     "SEISMIC_TOSS",
     "THUNDER_WAVE",
     "PRESENT"
    ]
   },
   {
    "species": "PIKACHU",
    "moves": [
     "THUNDERBOLT",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "RAICHU",
    "moves": [
     "THUNDERBOLT",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "cleffa",
  "role": "Bruiser",
  "blurb": "The Fairy Pokémon. Ability: Cute Charm.",
  "level": 54,
  "evoRate": 1.1,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "CLEFFA",
    "moves": [
     "PRESENT",
     "WATER_PULSE",
     "THUNDER_WAVE",
     "MAGICAL_LEAF"
    ]
   },
   {
    "species": "CLEFAIRY",
    "moves": [
     "BODY_SLAM",
     "ICE_BEAM",
     "CALM_MIND",
     "THUNDERBOLT"
    ]
   },
   {
    "species": "CLEFABLE",
    "moves": [
     "DOUBLE_EDGE",
     "FIRE_BLAST",
     "MOONLIGHT",
     "ICE_BEAM"
    ]
   }
  ]
 },
 {
  "id": "igglybuff",
  "role": "Balanced",
  "blurb": "The Balloon Pokémon. Ability: Cute Charm.",
  "level": 58,
  "evoRate": 1.1,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "IGGLYBUFF",
    "moves": [
     "PRESENT",
     "WATER_PULSE",
     "THUNDER_WAVE",
     "SHOCK_WAVE"
    ]
   },
   {
    "species": "JIGGLYPUFF",
    "moves": [
     "BODY_SLAM",
     "ICE_BEAM",
     "THUNDER_WAVE",
     "THUNDERBOLT"
    ]
   },
   {
    "species": "WIGGLYTUFF",
    "moves": [
     "DOUBLE_EDGE",
     "FIRE_BLAST",
     "THUNDER_WAVE",
     "ICE_BEAM"
    ]
   }
  ]
 },
 {
  "id": "togepi",
  "role": "Balanced",
  "blurb": "The Happiness Pokémon. Ability: Hustle.",
  "level": 56,
  "evoRate": 1.1,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "TOGEPI",
    "moves": [
     "BODY_SLAM",
     "PSYCHIC",
     "THUNDER_WAVE",
     "WATER_PULSE"
    ]
   },
   {
    "species": "TOGETIC",
    "moves": [
     "DOUBLE_EDGE",
     "AERIAL_ACE",
     "FIRE_BLAST",
     "SOFT_BOILED"
    ]
   }
  ]
 },
 {
  "id": "natu",
  "role": "Balanced",
  "blurb": "The Mystic Pokémon. Ability: Synchronize.",
  "level": 51,
  "evoRate": 1.2,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "NATU",
    "moves": [
     "PSYCHIC",
     "DRILL_PECK",
     "GIGA_DRAIN",
     "CALM_MIND"
    ]
   },
   {
    "species": "XATU",
    "moves": [
     "PSYCHIC",
     "DRILL_PECK",
     "SOLAR_BEAM",
     "CALM_MIND"
    ]
   }
  ]
 },
 {
  "id": "mareep",
  "role": "Special Nuker",
  "blurb": "The Light Pokémon. Ability: Static.",
  "level": 52,
  "evoRate": 2,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "MAREEP",
    "moves": [
     "SHOCK_WAVE",
     "TACKLE",
     "THUNDER_WAVE",
     "THUNDER_SHOCK"
    ]
   },
   {
    "species": "FLAAFFY",
    "moves": [
     "THUNDERBOLT",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "SHOCK_WAVE"
    ]
   },
   {
    "species": "AMPHAROS",
    "moves": [
     "THUNDERBOLT",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "sudowoodo",
  "role": "Balanced",
  "blurb": "The Imitation Pokémon. Ability: Sturdy.",
  "level": 55,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SUDOWOODO",
    "moves": [
     "ROCK_SLIDE",
     "EARTHQUAKE",
     "REST",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "hoppip",
  "role": "Speedster",
  "blurb": "The Cottonweed Pokémon. Ability: Chlorophyll.",
  "level": 56,
  "evoRate": 1.67,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "HOPPIP",
    "moves": [
     "GIGA_DRAIN",
     "AERIAL_ACE",
     "CONFUSION",
     "SWORDS_DANCE"
    ]
   },
   {
    "species": "SKIPLOOM",
    "moves": [
     "GIGA_DRAIN",
     "AERIAL_ACE",
     "CONFUSION",
     "SWORDS_DANCE"
    ]
   },
   {
    "species": "JUMPLUFF",
    "moves": [
     "SOLAR_BEAM",
     "AERIAL_ACE",
     "DOUBLE_EDGE",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "aipom",
  "role": "Balanced",
  "blurb": "The Long Tail Pokémon. Ability: Run Away.",
  "level": 59,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "AIPOM",
    "moves": [
     "DOUBLE_EDGE",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "sunkern",
  "role": "Balanced",
  "blurb": "The Sun Pokémon. Ability: Chlorophyll.",
  "level": 55,
  "evoRate": 1.1,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SUNKERN",
    "moves": [
     "GIGA_DRAIN",
     "SLUDGE_BOMB",
     "SWORDS_DANCE",
     "ENDEAVOR"
    ]
   },
   {
    "species": "SUNFLORA",
    "moves": [
     "SOLAR_BEAM",
     "SLUDGE_BOMB",
     "SYNTHESIS",
     "PETAL_DANCE"
    ]
   }
  ]
 },
 {
  "id": "yanma",
  "role": "Balanced",
  "blurb": "The Clear Wing Pokémon. Ability: Speed Boost.",
  "level": 57,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "YANMA",
    "moves": [
     "SIGNAL_BEAM",
     "WING_ATTACK",
     "SOLAR_BEAM",
     "HYPNOSIS"
    ]
   }
  ]
 },
 {
  "id": "wooper",
  "role": "Balanced",
  "blurb": "The Water Fish Pokémon. Ability: Damp.",
  "level": 54,
  "evoRate": 1.5,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "WOOPER",
    "moves": [
     "WATERFALL",
     "MUD_SHOT",
     "SLUDGE_BOMB",
     "AMNESIA"
    ]
   },
   {
    "species": "QUAGSIRE",
    "moves": [
     "SURF",
     "EARTHQUAKE",
     "BRICK_BREAK",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "murkrow",
  "role": "Balanced",
  "blurb": "The Darkness Pokémon. Ability: Insomnia.",
  "level": 55,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "MURKROW",
    "moves": [
     "FAINT_ATTACK",
     "SKY_ATTACK",
     "DOUBLE_EDGE",
     "THUNDER_WAVE"
    ]
   }
  ]
 },
 {
  "id": "misdreavus",
  "role": "Balanced",
  "blurb": "The Screech Pokémon. Ability: Levitate.",
  "level": 53,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "MISDREAVUS",
    "moves": [
     "SHADOW_BALL",
     "THUNDERBOLT",
     "CALM_MIND",
     "PSYCHIC"
    ]
   }
  ]
 },
 {
  "id": "unown",
  "role": "Balanced",
  "blurb": "The Symbol Pokémon. Ability: Levitate.",
  "level": 61,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "UNOWN",
    "moves": [
     "HIDDEN_POWER"
    ]
   }
  ]
 },
 {
  "id": "girafarig",
  "role": "Balanced",
  "blurb": "The Long Neck Pokémon. Ability: Inner Focus.",
  "level": 51,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "GIRAFARIG",
    "moves": [
     "DOUBLE_EDGE",
     "PSYCHIC",
     "EARTHQUAKE",
     "CALM_MIND"
    ]
   }
  ]
 },
 {
  "id": "pineco",
  "role": "Bruiser",
  "blurb": "The Bagworm Pokémon. Ability: Sturdy.",
  "level": 51,
  "evoRate": 0.97,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "PINECO",
    "moves": [
     "PIN_MISSILE",
     "ROCK_SLIDE",
     "BODY_SLAM",
     "STRENGTH"
    ]
   },
   {
    "species": "FORRETRESS",
    "moves": [
     "PIN_MISSILE",
     "EARTHQUAKE",
     "REST",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "dunsparce",
  "role": "Balanced",
  "blurb": "The Land Snake Pokémon. Ability: Serene Grace.",
  "level": 55,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "DUNSPARCE",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "gligar",
  "role": "Balanced",
  "blurb": "The Flyscorpion Pokémon. Ability: Hyper Cutter.",
  "level": 53,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "GLIGAR",
    "moves": [
     "EARTHQUAKE",
     "AERIAL_ACE",
     "DOUBLE_EDGE",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "snubbull",
  "role": "Heavy Hitter",
  "blurb": "The Fairy Pokémon. Ability: Intimidate.",
  "level": 53,
  "evoRate": 1.3,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SNUBBULL",
    "moves": [
     "BODY_SLAM",
     "BRICK_BREAK",
     "BULK_UP",
     "SLUDGE_BOMB"
    ]
   },
   {
    "species": "GRANBULL",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "BULK_UP",
     "SLUDGE_BOMB"
    ]
   }
  ]
 },
 {
  "id": "qwilfish",
  "role": "Balanced",
  "blurb": "The Balloon Pokémon. Ability: Poison Point.",
  "level": 53,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "QWILFISH",
    "moves": [
     "HYDRO_PUMP",
     "SLUDGE_BOMB",
     "REVENGE",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "shuckle",
  "role": "Tank",
  "blurb": "The Mold Pokémon. Ability: Sturdy.",
  "level": 47,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SHUCKLE",
    "moves": [
     "ROCK_SLIDE",
     "EARTHQUAKE",
     "REST",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "heracross",
  "role": "Heavy Hitter",
  "blurb": "The Single Horn Pokémon. Ability: Swarm.",
  "level": 48,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "HERACROSS",
    "moves": [
     "MEGAHORN",
     "BRICK_BREAK",
     "EARTHQUAKE",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "sneasel",
  "role": "Physical Sweeper",
  "blurb": "The Sharp Claw Pokémon. Ability: Inner Focus.",
  "level": 53,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SNEASEL",
    "moves": [
     "BITE",
     "ICE_BEAM",
     "BRICK_BREAK",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "teddiursa",
  "role": "Heavy Hitter",
  "blurb": "The Hibernator Pokémon. Ability: Guts.",
  "level": 48,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "TEDDIURSA",
    "moves": [
     "THRASH",
     "BRICK_BREAK",
     "SWORDS_DANCE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "URSARING",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "SWORDS_DANCE",
     "THRASH"
    ]
   }
  ]
 },
 {
  "id": "slugma",
  "role": "Balanced",
  "blurb": "The Lava Pokémon. Ability: Magma Armor.",
  "level": 56,
  "evoRate": 0.8,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SLUGMA",
    "moves": [
     "EMBER",
     "ROCK_SLIDE",
     "AMNESIA",
     "BODY_SLAM"
    ]
   },
   {
    "species": "MAGCARGO",
    "moves": [
     "OVERHEAT",
     "ROCK_SLIDE",
     "EARTHQUAKE",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "swinub",
  "role": "Balanced",
  "blurb": "The Swine Pokémon. Ability: Oblivious.",
  "level": 53,
  "evoRate": 0.91,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SWINUB",
    "moves": [
     "POWDER_SNOW",
     "MUD_SHOT",
     "ROCK_SLIDE",
     "AMNESIA"
    ]
   },
   {
    "species": "PILOSWINE",
    "moves": [
     "ICE_BEAM",
     "EARTHQUAKE",
     "DOUBLE_EDGE",
     "AMNESIA"
    ]
   }
  ]
 },
 {
  "id": "corsola",
  "role": "Balanced",
  "blurb": "The Coral Pokémon. Ability: Hustle.",
  "level": 58,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "CORSOLA",
    "moves": [
     "SURF",
     "ROCK_SLIDE",
     "ICE_BEAM",
     "CALM_MIND"
    ]
   }
  ]
 },
 {
  "id": "remoraid",
  "role": "Balanced",
  "blurb": "The Jet Pokémon. Ability: Suction Cups.",
  "level": 50,
  "evoRate": 1.2,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "REMORAID",
    "moves": [
     "WATERFALL",
     "PSYCHIC",
     "THUNDER_WAVE",
     "BUBBLE_BEAM"
    ]
   },
   {
    "species": "OCTILLERY",
    "moves": [
     "SURF",
     "FIRE_BLAST",
     "THUNDER_WAVE",
     "ICE_BEAM"
    ]
   }
  ]
 },
 {
  "id": "delibird",
  "role": "Balanced",
  "blurb": "The Delivery Pokémon. Ability: Vital Spirit.",
  "level": 62,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "DELIBIRD",
    "moves": [
     "ICE_BEAM",
     "AERIAL_ACE",
     "SEISMIC_TOSS",
     "BLIZZARD"
    ]
   }
  ]
 },
 {
  "id": "mantine",
  "role": "Bruiser",
  "blurb": "The Kite Pokémon. Ability: Swift Swim.",
  "level": 50,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "MANTINE",
    "moves": [
     "HYDRO_PUMP",
     "WING_ATTACK",
     "ICE_BEAM",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "skarmory",
  "role": "Bruiser",
  "blurb": "The Armor Bird Pokémon. Ability: Keen Eye.",
  "level": 50,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SKARMORY",
    "moves": [
     "STEEL_WING",
     "SKY_ATTACK",
     "DOUBLE_EDGE",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "phanpy",
  "role": "Heavy Hitter",
  "blurb": "The Armor Pokémon. Ability: Sturdy.",
  "level": 48,
  "evoRate": 1.2,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "PHANPY",
    "moves": [
     "ANCIENT_POWER",
     "BODY_SLAM",
     "STRENGTH",
     "TAKE_DOWN"
    ]
   },
   {
    "species": "DONPHAN",
    "moves": [
     "EARTHQUAKE",
     "ROCK_SLIDE",
     "REST",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "stantler",
  "role": "Balanced",
  "blurb": "The Big Horn Pokémon. Ability: Intimidate.",
  "level": 50,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "STANTLER",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "smeargle",
  "role": "Balanced",
  "blurb": "The Painter Pokémon. Ability: Own Tempo.",
  "level": 68,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SMEARGLE",
    "moves": [
     "SPORE",
     "EXTREME_SPEED",
     "BELLY_DRUM",
     "RECOVER"
    ]
   }
  ]
 },
 {
  "id": "tyrogue-hitmonchan",
  "role": "Balanced",
  "blurb": "The Punching Pokémon. Ability: Keen Eye.",
  "level": 52,
  "evoRate": 1.5,
  "tags": [
   "johto",
   "branch"
  ],
  "stages": [
   {
    "species": "TYROGUE",
    "moves": [
     "BRICK_BREAK",
     "ROCK_SLIDE",
     "BULK_UP",
     "BODY_SLAM"
    ]
   },
   {
    "species": "HITMONCHAN",
    "moves": [
     "REVENGE",
     "EARTHQUAKE",
     "BULK_UP",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "tyrogue-hitmonlee",
  "role": "Heavy Hitter",
  "blurb": "The Kicking Pokémon. Ability: Limber.",
  "level": 52,
  "evoRate": 1.5,
  "tags": [
   "johto",
   "branch"
  ],
  "stages": [
   {
    "species": "TYROGUE",
    "moves": [
     "BRICK_BREAK",
     "ROCK_SLIDE",
     "BULK_UP",
     "BODY_SLAM"
    ]
   },
   {
    "species": "HITMONLEE",
    "moves": [
     "REVENGE",
     "EARTHQUAKE",
     "BULK_UP",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "tyrogue-hitmontop",
  "role": "Bruiser",
  "blurb": "The Handstand Pokémon. Ability: Intimidate.",
  "level": 52,
  "evoRate": 1.5,
  "tags": [
   "johto",
   "branch"
  ],
  "stages": [
   {
    "species": "TYROGUE",
    "moves": [
     "BRICK_BREAK",
     "ROCK_SLIDE",
     "BULK_UP",
     "BODY_SLAM"
    ]
   },
   {
    "species": "HITMONTOP",
    "moves": [
     "REVENGE",
     "EARTHQUAKE",
     "BULK_UP",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "smoochum",
  "role": "Special Nuker",
  "blurb": "The Human Shape Pokémon. Ability: Oblivious.",
  "level": 52,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "SMOOCHUM",
    "moves": [
     "ICE_PUNCH",
     "PSYCHIC",
     "WATER_PULSE",
     "CALM_MIND"
    ]
   },
   {
    "species": "JYNX",
    "moves": [
     "ICE_BEAM",
     "PSYCHIC",
     "WATER_PULSE",
     "CALM_MIND"
    ]
   }
  ]
 },
 {
  "id": "elekid",
  "role": "Special Sweeper",
  "blurb": "The Electric Pokémon. Ability: Static.",
  "level": 49,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "ELEKID",
    "moves": [
     "THUNDER_PUNCH",
     "FIRE_PUNCH",
     "THUNDER_WAVE",
     "PSYCHIC"
    ]
   },
   {
    "species": "ELECTABUZZ",
    "moves": [
     "THUNDERBOLT",
     "FIRE_PUNCH",
     "THUNDER_WAVE",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "magby",
  "role": "Balanced",
  "blurb": "The Spitfire Pokémon. Ability: Flame Body.",
  "level": 49,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "MAGBY",
    "moves": [
     "FIRE_PUNCH",
     "PSYCHIC",
     "CONFUSE_RAY",
     "BODY_SLAM"
    ]
   },
   {
    "species": "MAGMAR",
    "moves": [
     "FIRE_BLAST",
     "PSYCHIC",
     "CONFUSE_RAY",
     "FLAMETHROWER"
    ]
   }
  ]
 },
 {
  "id": "miltank",
  "role": "Speedster",
  "blurb": "The Milk Cow Pokémon. Ability: Thick Fat.",
  "level": 48,
  "tags": [
   "johto"
  ],
  "stages": [
   {
    "species": "MILTANK",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "MILK_DRINK",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "raikou",
  "role": "Legendary",
  "blurb": "The Thunder Pokémon. Ability: Pressure.",
  "level": 41,
  "tags": [
   "johto",
   "legendary"
  ],
  "stages": [
   {
    "species": "RAIKOU",
    "moves": [
     "THUNDERBOLT",
     "CRUNCH",
     "CALM_MIND",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "entei",
  "role": "Legendary",
  "blurb": "The Volcano Pokémon. Ability: Pressure.",
  "level": 41,
  "tags": [
   "johto",
   "legendary"
  ],
  "stages": [
   {
    "species": "ENTEI",
    "moves": [
     "FIRE_BLAST",
     "DOUBLE_EDGE",
     "REST",
     "IRON_TAIL"
    ]
   }
  ]
 },
 {
  "id": "suicune",
  "role": "Legendary",
  "blurb": "The Aurora Pokémon. Ability: Pressure.",
  "level": 41,
  "tags": [
   "johto",
   "legendary"
  ],
  "stages": [
   {
    "species": "SUICUNE",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "CALM_MIND",
     "SURF"
    ]
   }
  ]
 },
 {
  "id": "lugia",
  "role": "Legendary",
  "blurb": "The Diving Pokémon. Ability: Pressure.",
  "level": 33,
  "tags": [
   "johto",
   "legendary"
  ],
  "stages": [
   {
    "species": "LUGIA",
    "moves": [
     "PSYCHIC",
     "AEROBLAST",
     "EARTHQUAKE",
     "RECOVER"
    ]
   }
  ]
 },
 {
  "id": "ho-oh",
  "role": "Legendary",
  "blurb": "The Rainbow Pokémon. Ability: Pressure.",
  "level": 33,
  "tags": [
   "johto",
   "legendary"
  ],
  "stages": [
   {
    "species": "HO_OH",
    "moves": [
     "OVERHEAT",
     "AERIAL_ACE",
     "EARTHQUAKE",
     "RECOVER"
    ]
   }
  ]
 },
 {
  "id": "celebi",
  "role": "Legendary",
  "blurb": "The Time Travel Pokémon. Ability: Natural Cure.",
  "level": 39,
  "tags": [
   "johto",
   "legendary"
  ],
  "stages": [
   {
    "species": "CELEBI",
    "moves": [
     "PSYCHIC",
     "SOLAR_BEAM",
     "SHADOW_BALL",
     "RECOVER"
    ]
   }
  ]
 },
 {
  "id": "treecko",
  "role": "Special Sweeper",
  "blurb": "The Forest Pokémon. Ability: Overgrow.",
  "level": 49,
  "evoRate": 1.88,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "TREECKO",
    "moves": [
     "GIGA_DRAIN",
     "DRAGON_BREATH",
     "AGILITY",
     "MEGA_DRAIN"
    ]
   },
   {
    "species": "GROVYLE",
    "moves": [
     "LEAF_BLADE",
     "CRUNCH",
     "AGILITY",
     "DRAGON_BREATH"
    ]
   },
   {
    "species": "SCEPTILE",
    "moves": [
     "SOLAR_BEAM",
     "EARTHQUAKE",
     "AGILITY",
     "CRUNCH"
    ]
   }
  ]
 },
 {
  "id": "torchic",
  "role": "Heavy Hitter",
  "blurb": "The Blaze Pokémon. Ability: Blaze.",
  "level": 49,
  "evoRate": 1.88,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "TORCHIC",
    "moves": [
     "EMBER",
     "SEISMIC_TOSS",
     "SLASH",
     "AERIAL_ACE"
    ]
   },
   {
    "species": "COMBUSKEN",
    "moves": [
     "FLAMETHROWER",
     "SKY_UPPERCUT",
     "ROCK_SLIDE",
     "BULK_UP"
    ]
   },
   {
    "species": "BLAZIKEN",
    "moves": [
     "OVERHEAT",
     "SKY_UPPERCUT",
     "EARTHQUAKE",
     "BULK_UP"
    ]
   }
  ]
 },
 {
  "id": "mudkip",
  "role": "Heavy Hitter",
  "blurb": "The Mud Fish Pokémon. Ability: Torrent.",
  "level": 49,
  "evoRate": 1.88,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "MUDKIP",
    "moves": [
     "WATER_PULSE",
     "STOMP",
     "ROCK_TOMB",
     "DIG"
    ]
   },
   {
    "species": "MARSHTOMP",
    "moves": [
     "SURF",
     "MUD_SHOT",
     "ROCK_SLIDE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "SWAMPERT",
    "moves": [
     "HYDRO_PUMP",
     "EARTHQUAKE",
     "BRICK_BREAK",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "poochyena",
  "role": "Balanced",
  "blurb": "The Bite Pokémon. Ability: Intimidate.",
  "level": 55,
  "evoRate": 1.67,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "POOCHYENA",
    "moves": [
     "CRUNCH",
     "BODY_SLAM",
     "HOWL",
     "SHADOW_BALL"
    ]
   },
   {
    "species": "MIGHTYENA",
    "moves": [
     "CRUNCH",
     "IRON_TAIL",
     "HOWL",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "zigzagoon",
  "role": "Speedster",
  "blurb": "The Rushing Pokémon. Ability: Pickup.",
  "level": 55,
  "evoRate": 1.5,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "ZIGZAGOON",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "BELLY_DRUM",
     "HEADBUTT"
    ]
   },
   {
    "species": "LINOONE",
    "moves": [
     "DOUBLE_EDGE",
     "SHADOW_BALL",
     "BELLY_DRUM",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "wurmple-beautifly",
  "role": "Balanced",
  "blurb": "The Butterfly Pokémon. Ability: Swarm.",
  "level": 61,
  "evoRate": 2.5,
  "tags": [
   "hoenn",
   "branch"
  ],
  "stages": [
   {
    "species": "WURMPLE",
    "moves": [
     "TACKLE",
     "POISON_STING"
    ]
   },
   {
    "species": "SILCOON",
    "moves": [
     "TACKLE",
     "POISON_STING",
     "HARDEN"
    ]
   },
   {
    "species": "BEAUTIFLY",
    "moves": [
     "SILVER_WIND",
     "AERIAL_ACE",
     "SOLAR_BEAM",
     "MORNING_SUN"
    ]
   }
  ]
 },
 {
  "id": "wurmple-dustox",
  "role": "Balanced",
  "blurb": "The Poison Moth Pokémon. Ability: Shield Dust.",
  "level": 61,
  "evoRate": 2.5,
  "tags": [
   "hoenn",
   "branch"
  ],
  "stages": [
   {
    "species": "WURMPLE",
    "moves": [
     "TACKLE",
     "POISON_STING"
    ]
   },
   {
    "species": "CASCOON",
    "moves": [
     "TACKLE",
     "POISON_STING",
     "HARDEN"
    ]
   },
   {
    "species": "DUSTOX",
    "moves": [
     "SILVER_WIND",
     "SLUDGE_BOMB",
     "PSYCHIC",
     "MOONLIGHT"
    ]
   }
  ]
 },
 {
  "id": "lotad",
  "role": "Balanced",
  "blurb": "The Carefree Pokémon. Ability: Swift Swim.",
  "level": 53,
  "evoRate": 2.14,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "LOTAD",
    "moves": [
     "WATER_PULSE",
     "GIGA_DRAIN",
     "FLAIL",
     "LEECH_SEED"
    ]
   },
   {
    "species": "LOMBRE",
    "moves": [
     "SURF",
     "GIGA_DRAIN",
     "ICE_BEAM",
     "LEECH_SEED"
    ]
   },
   {
    "species": "LUDICOLO",
    "moves": [
     "HYDRO_PUMP",
     "SOLAR_BEAM",
     "ICE_BEAM",
     "SYNTHESIS"
    ]
   }
  ]
 },
 {
  "id": "seedot",
  "role": "Balanced",
  "blurb": "The Wicked Pokémon. Ability: Chlorophyll.",
  "level": 53,
  "evoRate": 2.14,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SEEDOT",
    "moves": [
     "GIGA_DRAIN",
     "DIG",
     "SWORDS_DANCE",
     "QUICK_ATTACK"
    ]
   },
   {
    "species": "NUZLEAF",
    "moves": [
     "GIGA_DRAIN",
     "FAINT_ATTACK",
     "BRICK_BREAK",
     "SWORDS_DANCE"
    ]
   },
   {
    "species": "SHIFTRY",
    "moves": [
     "SOLAR_BEAM",
     "FAINT_ATTACK",
     "BRICK_BREAK",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "taillow",
  "role": "Speedster",
  "blurb": "The Swallow Pokémon. Ability: Guts.",
  "level": 54,
  "evoRate": 1.36,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "TAILLOW",
    "moves": [
     "ENDEAVOR",
     "WING_ATTACK",
     "STEEL_WING",
     "AGILITY"
    ]
   },
   {
    "species": "SWELLOW",
    "moves": [
     "DOUBLE_EDGE",
     "SKY_ATTACK",
     "STEEL_WING",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "wingull",
  "role": "Balanced",
  "blurb": "The Water Bird Pokémon. Ability: Keen Eye.",
  "level": 54,
  "evoRate": 1.2,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "WINGULL",
    "moves": [
     "WATER_PULSE",
     "WING_ATTACK",
     "SHOCK_WAVE",
     "AGILITY"
    ]
   },
   {
    "species": "PELIPPER",
    "moves": [
     "HYDRO_PUMP",
     "WING_ATTACK",
     "ICE_BEAM",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "ralts",
  "role": "Special Nuker",
  "blurb": "The Embrace Pokémon. Ability: Synchronize.",
  "level": 50,
  "evoRate": 1.5,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "RALTS",
    "moves": [
     "CONFUSION",
     "SHOCK_WAVE",
     "CALM_MIND",
     "PSYCHIC"
    ]
   },
   {
    "species": "KIRLIA",
    "moves": [
     "PSYCHIC",
     "THUNDERBOLT",
     "CALM_MIND",
     "MAGICAL_LEAF"
    ]
   },
   {
    "species": "GARDEVOIR",
    "moves": [
     "PSYCHIC",
     "THUNDERBOLT",
     "CALM_MIND",
     "MAGICAL_LEAF"
    ]
   }
  ]
 },
 {
  "id": "surskit",
  "role": "Balanced",
  "blurb": "The Eyeball Pokémon. Ability: Intimidate.",
  "level": 56,
  "evoRate": 1.36,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SURSKIT",
    "moves": [
     "BUBBLE_BEAM",
     "PSYBEAM",
     "AGILITY",
     "WATER_PULSE"
    ]
   },
   {
    "species": "MASQUERAIN",
    "moves": [
     "SILVER_WIND",
     "AERIAL_ACE",
     "ICE_BEAM",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "shroomish",
  "role": "Heavy Hitter",
  "blurb": "The Mushroom Pokémon. Ability: Effect Spore.",
  "level": 52,
  "evoRate": 1.3,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SHROOMISH",
    "moves": [
     "GIGA_DRAIN",
     "SLUDGE_BOMB",
     "SPORE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "BRELOOM",
    "moves": [
     "SOLAR_BEAM",
     "SKY_UPPERCUT",
     "SLUDGE_BOMB",
     "SPORE"
    ]
   }
  ]
 },
 {
  "id": "slakoth",
  "role": "Physical Sweeper",
  "blurb": "The Lazy Pokémon. Ability: Truant.",
  "level": 38,
  "evoRate": 1.67,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SLAKOTH",
    "moves": [
     "SLASH",
     "SEISMIC_TOSS",
     "BULK_UP",
     "FLAIL"
    ]
   },
   {
    "species": "VIGOROTH",
    "moves": [
     "BODY_SLAM",
     "BRICK_BREAK",
     "BULK_UP",
     "SHADOW_BALL"
    ]
   },
   {
    "species": "SLAKING",
    "moves": [
     "DOUBLE_EDGE",
     "EARTHQUAKE",
     "SLACK_OFF",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "nincada-ninjask",
  "role": "Physical Sweeper",
  "blurb": "The Ninja Pokémon. Ability: Speed Boost.",
  "level": 52,
  "evoRate": 1.5,
  "tags": [
   "hoenn",
   "branch"
  ],
  "stages": [
   {
    "species": "NINCADA",
    "moves": [
     "SILVER_WIND",
     "DIG",
     "SHADOW_BALL",
     "AERIAL_ACE"
    ]
   },
   {
    "species": "NINJASK",
    "moves": [
     "SILVER_WIND",
     "AERIAL_ACE",
     "DOUBLE_EDGE",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "nincada-shedinja",
  "role": "Balanced",
  "blurb": "The Shed Pokémon. Ability: Wonder Guard.",
  "level": 70,
  "evoRate": 1.5,
  "tags": [
   "hoenn",
   "branch"
  ],
  "stages": [
   {
    "species": "NINCADA",
    "moves": [
     "SILVER_WIND",
     "DIG",
     "SHADOW_BALL",
     "AERIAL_ACE"
    ]
   },
   {
    "species": "SHEDINJA",
    "moves": [
     "SILVER_WIND",
     "SHADOW_BALL",
     "DOUBLE_EDGE",
     "CONFUSE_RAY"
    ]
   }
  ]
 },
 {
  "id": "whismur",
  "role": "Balanced",
  "blurb": "The Loud Noise Pokémon. Ability: Soundproof.",
  "level": 53,
  "evoRate": 1.5,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "WHISMUR",
    "moves": [
     "SMELLING_SALT",
     "SEISMIC_TOSS",
     "HOWL",
     "STOMP"
    ]
   },
   {
    "species": "LOUDRED",
    "moves": [
     "HYPER_VOICE",
     "ICE_BEAM",
     "HOWL",
     "FLAMETHROWER"
    ]
   },
   {
    "species": "EXPLOUD",
    "moves": [
     "DOUBLE_EDGE",
     "OVERHEAT",
     "HOWL",
     "ICE_BEAM"
    ]
   }
  ]
 },
 {
  "id": "makuhita",
  "role": "Heavy Hitter",
  "blurb": "The Arm Thrust Pokémon. Ability: Thick Fat.",
  "level": 51,
  "evoRate": 1.25,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "MAKUHITA",
    "moves": [
     "VITAL_THROW",
     "ROCK_SLIDE",
     "BULK_UP",
     "BODY_SLAM"
    ]
   },
   {
    "species": "HARIYAMA",
    "moves": [
     "CROSS_CHOP",
     "EARTHQUAKE",
     "BULK_UP",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "azurill",
  "role": "Bruiser",
  "blurb": "The Aqua Rabbit Pokémon. Ability: Thick Fat.",
  "level": 59,
  "evoRate": 1.1,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "AZURILL",
    "moves": [
     "WATER_PULSE",
     "SING",
     "WATER_GUN",
     "BUBBLE"
    ]
   },
   {
    "species": "MARILL",
    "moves": [
     "SURF",
     "ICE_BEAM",
     "BELLY_DRUM",
     "BODY_SLAM"
    ]
   },
   {
    "species": "AZUMARILL",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "BELLY_DRUM",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "nosepass",
  "role": "Bruiser",
  "blurb": "The Compass Pokémon. Ability: Sturdy.",
  "level": 58,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "NOSEPASS",
    "moves": [
     "ROCK_SLIDE",
     "EARTHQUAKE",
     "THUNDER_WAVE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "skitty",
  "role": "Balanced",
  "blurb": "The Prim Pokémon. Ability: Cute Charm.",
  "level": 58,
  "evoRate": 1.1,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SKITTY",
    "moves": [
     "BODY_SLAM",
     "SHADOW_BALL",
     "THUNDER_WAVE",
     "COVET"
    ]
   },
   {
    "species": "DELCATTY",
    "moves": [
     "DOUBLE_EDGE",
     "ICE_BEAM",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "sableye",
  "role": "Balanced",
  "blurb": "The Darkness Pokémon. Ability: Keen Eye.",
  "level": 58,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SABLEYE",
    "moves": [
     "FAINT_ATTACK",
     "SHADOW_BALL",
     "BRICK_BREAK",
     "RECOVER"
    ]
   }
  ]
 },
 {
  "id": "mawile",
  "role": "Balanced",
  "blurb": "The Deceiver Pokémon. Ability: Hyper Cutter.",
  "level": 58,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "MAWILE",
    "moves": [
     "BRICK_BREAK",
     "SWORDS_DANCE",
     "DOUBLE_EDGE",
     "SLUDGE_BOMB"
    ]
   }
  ]
 },
 {
  "id": "aron",
  "role": "Heavy Hitter",
  "blurb": "The Iron Armor Pokémon. Ability: Sturdy.",
  "level": 49,
  "evoRate": 0.94,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "ARON",
    "moves": [
     "METAL_CLAW",
     "ROCK_TOMB",
     "AERIAL_ACE",
     "IRON_DEFENSE"
    ]
   },
   {
    "species": "LAIRON",
    "moves": [
     "METAL_CLAW",
     "ROCK_SLIDE",
     "BODY_SLAM",
     "REST"
    ]
   },
   {
    "species": "AGGRON",
    "moves": [
     "IRON_TAIL",
     "ROCK_SLIDE",
     "EARTHQUAKE",
     "THUNDER_WAVE"
    ]
   }
  ]
 },
 {
  "id": "meditite",
  "role": "Balanced",
  "blurb": "The Meditate Pokémon. Ability: Pure Power.",
  "level": 56,
  "evoRate": 0.81,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "MEDITITE",
    "moves": [
     "HI_JUMP_KICK",
     "PSYCHIC",
     "ICE_PUNCH",
     "BULK_UP"
    ]
   },
   {
    "species": "MEDICHAM",
    "moves": [
     "HI_JUMP_KICK",
     "PSYCHIC",
     "ICE_PUNCH",
     "BULK_UP"
    ]
   }
  ]
 },
 {
  "id": "electrike",
  "role": "Special Sweeper",
  "blurb": "The Discharge Pokémon. Ability: Static.",
  "level": 50,
  "evoRate": 1.15,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "ELECTRIKE",
    "moves": [
     "SPARK",
     "CRUNCH",
     "THUNDER_WAVE",
     "SHOCK_WAVE"
    ]
   },
   {
    "species": "MANECTRIC",
    "moves": [
     "THUNDERBOLT",
     "CRUNCH",
     "THUNDER_WAVE",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "plusle",
  "role": "Balanced",
  "blurb": "The Cheering Pokémon. Ability: Plus.",
  "level": 55,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "PLUSLE",
    "moves": [
     "THUNDERBOLT",
     "SEISMIC_TOSS",
     "THUNDER_WAVE",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "minun",
  "role": "Balanced",
  "blurb": "The Cheering Pokémon. Ability: Minus.",
  "level": 55,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "MINUN",
    "moves": [
     "THUNDERBOLT",
     "SEISMIC_TOSS",
     "THUNDER_WAVE",
     "THUNDER"
    ]
   }
  ]
 },
 {
  "id": "volbeat",
  "role": "Balanced",
  "blurb": "The Firefly Pokémon. Ability: Illuminate.",
  "level": 56,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "VOLBEAT",
    "moves": [
     "SIGNAL_BEAM",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "illumise",
  "role": "Balanced",
  "blurb": "The Firefly Pokémon. Ability: Oblivious.",
  "level": 56,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "ILLUMISE",
    "moves": [
     "SILVER_WIND",
     "THUNDERBOLT",
     "THUNDER_WAVE",
     "SOLAR_BEAM"
    ]
   }
  ]
 },
 {
  "id": "roselia",
  "role": "Balanced",
  "blurb": "The Thorn Pokémon. Ability: Natural Cure.",
  "level": 56,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "ROSELIA",
    "moves": [
     "PETAL_DANCE",
     "SLUDGE_BOMB",
     "SHADOW_BALL",
     "LEECH_SEED"
    ]
   }
  ]
 },
 {
  "id": "gulpin",
  "role": "Bruiser",
  "blurb": "The Poison Bag Pokémon. Ability: Liquid Ooze.",
  "level": 51,
  "evoRate": 1.15,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "GULPIN",
    "moves": [
     "SLUDGE_BOMB",
     "SHADOW_BALL",
     "AMNESIA",
     "BODY_SLAM"
    ]
   },
   {
    "species": "SWALOT",
    "moves": [
     "SLUDGE_BOMB",
     "ICE_BEAM",
     "REST",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "carvanha",
  "role": "Heavy Hitter",
  "blurb": "The Brutal Pokémon. Ability: Rough Skin.",
  "level": 52,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "CARVANHA",
    "moves": [
     "WATERFALL",
     "CRUNCH",
     "THRASH",
     "AGILITY"
    ]
   },
   {
    "species": "SHARPEDO",
    "moves": [
     "HYDRO_PUMP",
     "CRUNCH",
     "EARTHQUAKE",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "wailmer",
  "role": "Bruiser",
  "blurb": "The Float Whale Pokémon. Ability: Water Veil.",
  "level": 48,
  "evoRate": 0.8,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "WAILMER",
    "moves": [
     "WATERFALL",
     "THRASH",
     "AMNESIA",
     "WATER_PULSE"
    ]
   },
   {
    "species": "WAILORD",
    "moves": [
     "WATER_SPOUT",
     "ICE_BEAM",
     "REST",
     "HYDRO_PUMP"
    ]
   }
  ]
 },
 {
  "id": "numel",
  "role": "Balanced",
  "blurb": "The Eruption Pokémon. Ability: Magma Armor.",
  "level": 52,
  "evoRate": 0.91,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "NUMEL",
    "moves": [
     "EMBER",
     "MAGNITUDE",
     "BODY_SLAM",
     "AMNESIA"
    ]
   },
   {
    "species": "CAMERUPT",
    "moves": [
     "OVERHEAT",
     "EARTHQUAKE",
     "DOUBLE_EDGE",
     "AMNESIA"
    ]
   }
  ]
 },
 {
  "id": "torkoal",
  "role": "Bruiser",
  "blurb": "The Coal Pokémon. Ability: White Smoke.",
  "level": 50,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "TORKOAL",
    "moves": [
     "OVERHEAT",
     "DOUBLE_EDGE",
     "REST",
     "FLAMETHROWER"
    ]
   }
  ]
 },
 {
  "id": "spoink",
  "role": "Bruiser",
  "blurb": "The Manipulate Pokémon. Ability: Thick Fat.",
  "level": 51,
  "evoRate": 0.94,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SPOINK",
    "moves": [
     "PSYCHIC",
     "SHOCK_WAVE",
     "CALM_MIND",
     "EXTRASENSORY"
    ]
   },
   {
    "species": "GRUMPIG",
    "moves": [
     "PSYCHIC",
     "SHOCK_WAVE",
     "CALM_MIND",
     "EXTRASENSORY"
    ]
   }
  ]
 },
 {
  "id": "spinda",
  "role": "Balanced",
  "blurb": "The Spot Panda Pokémon. Ability: Own Tempo.",
  "level": 59,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SPINDA",
    "moves": [
     "DOUBLE_EDGE",
     "BRICK_BREAK",
     "HYPNOSIS",
     "THRASH"
    ]
   }
  ]
 },
 {
  "id": "trapinch",
  "role": "Physical Sweeper",
  "blurb": "The Mystic Pokémon. Ability: Levitate.",
  "level": 50,
  "evoRate": 0.86,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "TRAPINCH",
    "moves": [
     "DIG",
     "ROCK_TOMB",
     "QUICK_ATTACK",
     "GUST"
    ]
   },
   {
    "species": "VIBRAVA",
    "moves": [
     "DIG",
     "DRAGON_BREATH",
     "ROCK_SLIDE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "FLYGON",
    "moves": [
     "EARTHQUAKE",
     "DRAGON_CLAW",
     "FIRE_BLAST",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "cacnea",
  "role": "Heavy Hitter",
  "blurb": "The Scarecrow Pokémon. Ability: Sand Veil.",
  "level": 50,
  "evoRate": 0.94,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "CACNEA",
    "moves": [
     "NEEDLE_ARM",
     "SEISMIC_TOSS",
     "SWORDS_DANCE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "CACTURNE",
    "moves": [
     "SOLAR_BEAM",
     "FAINT_ATTACK",
     "REVENGE",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "swablu",
  "role": "Bruiser",
  "blurb": "The Humming Pokémon. Ability: Natural Cure.",
  "level": 49,
  "evoRate": 0.86,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SWABLU",
    "moves": [
     "BODY_SLAM",
     "AERIAL_ACE",
     "STEEL_WING",
     "AGILITY"
    ]
   },
   {
    "species": "ALTARIA",
    "moves": [
     "DRAGON_CLAW",
     "SKY_ATTACK",
     "EARTHQUAKE",
     "DRAGON_DANCE"
    ]
   }
  ]
 },
 {
  "id": "zangoose",
  "role": "Heavy Hitter",
  "blurb": "The Cat Ferret Pokémon. Ability: Immunity.",
  "level": 51,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "ZANGOOSE",
    "moves": [
     "DOUBLE_EDGE",
     "BRICK_BREAK",
     "SWORDS_DANCE",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "seviper",
  "role": "Balanced",
  "blurb": "The Fang Snake Pokémon. Ability: Shed Skin.",
  "level": 51,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SEVIPER",
    "moves": [
     "SLUDGE_BOMB",
     "EARTHQUAKE",
     "GLARE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "lunatone",
  "role": "Balanced",
  "blurb": "The Meteorite Pokémon. Ability: Levitate.",
  "level": 53,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "LUNATONE",
    "moves": [
     "ROCK_SLIDE",
     "PSYCHIC",
     "ICE_BEAM",
     "CALM_MIND"
    ]
   }
  ]
 },
 {
  "id": "solrock",
  "role": "Balanced",
  "blurb": "The Meteorite Pokémon. Ability: Levitate.",
  "level": 53,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SOLROCK",
    "moves": [
     "ROCK_SLIDE",
     "PSYCHIC",
     "EARTHQUAKE",
     "COSMIC_POWER"
    ]
   }
  ]
 },
 {
  "id": "barboach",
  "role": "Balanced",
  "blurb": "The Whiskers Pokémon. Ability: Oblivious.",
  "level": 51,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "BARBOACH",
    "moves": [
     "WATERFALL",
     "MAGNITUDE",
     "THRASH",
     "AMNESIA"
    ]
   },
   {
    "species": "WHISCASH",
    "moves": [
     "SURF",
     "EARTHQUAKE",
     "ICE_BEAM",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "corphish",
  "role": "Heavy Hitter",
  "blurb": "The Rogue Pokémon. Ability: Hyper Cutter.",
  "level": 51,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "CORPHISH",
    "moves": [
     "CRABHAMMER",
     "BRICK_BREAK",
     "SWORDS_DANCE",
     "SLUDGE_BOMB"
    ]
   },
   {
    "species": "CRAWDAUNT",
    "moves": [
     "SURF",
     "CRUNCH",
     "BRICK_BREAK",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "baltoy",
  "role": "Tank",
  "blurb": "The Clay Doll Pokémon. Ability: Levitate.",
  "level": 48,
  "evoRate": 0.83,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "BALTOY",
    "moves": [
     "DIG",
     "PSYCHIC",
     "SHADOW_BALL",
     "COSMIC_POWER"
    ]
   },
   {
    "species": "CLAYDOL",
    "moves": [
     "EARTHQUAKE",
     "PSYCHIC",
     "ICE_BEAM",
     "COSMIC_POWER"
    ]
   }
  ]
 },
 {
  "id": "lileep",
  "role": "Tank",
  "blurb": "The Barnacle Pokémon. Ability: Suction Cups.",
  "level": 49,
  "evoRate": 0.8,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "LILEEP",
    "moves": [
     "ROCK_SLIDE",
     "GIGA_DRAIN",
     "SLUDGE_BOMB",
     "RECOVER"
    ]
   },
   {
    "species": "CRADILY",
    "moves": [
     "ROCK_SLIDE",
     "SOLAR_BEAM",
     "EARTHQUAKE",
     "RECOVER"
    ]
   }
  ]
 },
 {
  "id": "anorith",
  "role": "Heavy Hitter",
  "blurb": "The Plate Pokémon. Ability: Battle Armor.",
  "level": 49,
  "evoRate": 0.8,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "ANORITH",
    "moves": [
     "ROCK_SLIDE",
     "FURY_CUTTER",
     "BRICK_BREAK",
     "SWORDS_DANCE"
    ]
   },
   {
    "species": "ARMALDO",
    "moves": [
     "ROCK_SLIDE",
     "FURY_CUTTER",
     "EARTHQUAKE",
     "SWORDS_DANCE"
    ]
   }
  ]
 },
 {
  "id": "feebas",
  "role": "Bruiser",
  "blurb": "The Tender Pokémon. Ability: Marvel Scale.",
  "level": 45,
  "evoRate": 1.1,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "FEEBAS",
    "moves": [
     "WATERFALL",
     "FLAIL",
     "HYPNOSIS",
     "WATER_PULSE"
    ]
   },
   {
    "species": "MILOTIC",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "RECOVER",
     "SURF"
    ]
   }
  ]
 },
 {
  "id": "castform",
  "role": "Balanced",
  "blurb": "The Weather Pokémon. Ability: Forecast.",
  "level": 54,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "CASTFORM",
    "moves": [
     "DOUBLE_EDGE",
     "FIRE_BLAST",
     "THUNDER_WAVE",
     "ICE_BEAM"
    ]
   }
  ]
 },
 {
  "id": "kecleon",
  "role": "Balanced",
  "blurb": "The Color Swap Pokémon. Ability: Color Change.",
  "level": 53,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "KECLEON",
    "moves": [
     "DOUBLE_EDGE",
     "BRICK_BREAK",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   }
  ]
 },
 {
  "id": "shuppet",
  "role": "Heavy Hitter",
  "blurb": "The Marionette Pokémon. Ability: Insomnia.",
  "level": 52,
  "evoRate": 0.81,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SHUPPET",
    "moves": [
     "SHADOW_BALL",
     "PSYCHIC",
     "THUNDER_WAVE",
     "BODY_SLAM"
    ]
   },
   {
    "species": "BANETTE",
    "moves": [
     "SHADOW_BALL",
     "DOUBLE_EDGE",
     "THUNDER_WAVE",
     "NIGHT_SHADE"
    ]
   }
  ]
 },
 {
  "id": "duskull",
  "role": "Tank",
  "blurb": "The Beckon Pokémon. Ability: Pressure.",
  "level": 52,
  "evoRate": 0.81,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "DUSKULL",
    "moves": [
     "SHADOW_BALL",
     "BODY_SLAM",
     "CONFUSE_RAY",
     "NIGHT_SHADE"
    ]
   },
   {
    "species": "DUSCLOPS",
    "moves": [
     "SHADOW_BALL",
     "EARTHQUAKE",
     "REST",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "tropius",
  "role": "Bruiser",
  "blurb": "The Fruit Pokémon. Ability: Chlorophyll.",
  "level": 51,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "TROPIUS",
    "moves": [
     "SOLAR_BEAM",
     "AERIAL_ACE",
     "EARTHQUAKE",
     "SYNTHESIS"
    ]
   }
  ]
 },
 {
  "id": "chimecho",
  "role": "Balanced",
  "blurb": "The Wind Chime Pokémon. Ability: Levitate.",
  "level": 54,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "CHIMECHO",
    "moves": [
     "PSYCHIC",
     "SHOCK_WAVE",
     "CALM_MIND",
     "CONFUSION"
    ]
   }
  ]
 },
 {
  "id": "absol",
  "role": "Heavy Hitter",
  "blurb": "The Disaster Pokémon. Ability: Pressure.",
  "level": 50,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "ABSOL",
    "moves": [
     "BITE",
     "ROCK_SLIDE",
     "SWORDS_DANCE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "wynaut",
  "role": "Tank",
  "blurb": "The Patient Pokémon. Ability: Shadow Tag.",
  "level": 56,
  "evoRate": 2,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "WYNAUT",
    "moves": [
     "MIRROR_COAT",
     "COUNTER",
     "CHARM"
    ]
   },
   {
    "species": "WOBBUFFET",
    "moves": [
     "MIRROR_COAT",
     "COUNTER",
     "CHARM"
    ]
   }
  ]
 },
 {
  "id": "snorunt",
  "role": "Balanced",
  "blurb": "The Face Pokémon. Ability: Inner Focus.",
  "level": 50,
  "evoRate": 0.8,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SNORUNT",
    "moves": [
     "ICY_WIND",
     "CRUNCH",
     "BODY_SLAM",
     "SHADOW_BALL"
    ]
   },
   {
    "species": "GLALIE",
    "moves": [
     "ICE_BEAM",
     "EARTHQUAKE",
     "DOUBLE_EDGE",
     "CRUNCH"
    ]
   }
  ]
 },
 {
  "id": "spheal",
  "role": "Bruiser",
  "blurb": "The Ice Break Pokémon. Ability: Thick Fat.",
  "level": 49,
  "evoRate": 0.94,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "SPHEAL",
    "moves": [
     "AURORA_BEAM",
     "WATER_PULSE",
     "ROCK_TOMB",
     "POWDER_SNOW"
    ]
   },
   {
    "species": "SEALEO",
    "moves": [
     "ICE_BEAM",
     "SURF",
     "BODY_SLAM",
     "WATERFALL"
    ]
   },
   {
    "species": "WALREIN",
    "moves": [
     "ICE_BEAM",
     "SURF",
     "EARTHQUAKE",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "clamperl-huntail",
  "role": "Balanced",
  "blurb": "The Deep Sea Pokémon. Ability: Swift Swim.",
  "level": 50,
  "evoRate": 1.1,
  "tags": [
   "hoenn",
   "branch"
  ],
  "stages": [
   {
    "species": "CLAMPERL",
    "moves": [
     "WATERFALL",
     "BODY_SLAM",
     "CONFUSE_RAY",
     "WATER_PULSE"
    ]
   },
   {
    "species": "HUNTAIL",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "CONFUSE_RAY",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "clamperl-gorebyss",
  "role": "Special Nuker",
  "blurb": "The South Sea Pokémon. Ability: Swift Swim.",
  "level": 50,
  "evoRate": 1.1,
  "tags": [
   "hoenn",
   "branch"
  ],
  "stages": [
   {
    "species": "CLAMPERL",
    "moves": [
     "WATERFALL",
     "BODY_SLAM",
     "CONFUSE_RAY",
     "WATER_PULSE"
    ]
   },
   {
    "species": "GOREBYSS",
    "moves": [
     "HYDRO_PUMP",
     "ICE_BEAM",
     "AGILITY",
     "PSYCHIC"
    ]
   }
  ]
 },
 {
  "id": "relicanth",
  "role": "Bruiser",
  "blurb": "The Longevity Pokémon. Ability: Swift Swim.",
  "level": 49,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "RELICANTH",
    "moves": [
     "HYDRO_PUMP",
     "ROCK_SLIDE",
     "EARTHQUAKE",
     "REST"
    ]
   }
  ]
 },
 {
  "id": "luvdisc",
  "role": "Balanced",
  "blurb": "The Rendezvous Pokémon. Ability: Swift Swim.",
  "level": 62,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "LUVDISC",
    "moves": [
     "SURF",
     "ICE_BEAM",
     "AGILITY",
     "WATERFALL"
    ]
   }
  ]
 },
 {
  "id": "bagon",
  "role": "Physical Sweeper",
  "blurb": "The Dragon Pokémon. Ability: Intimidate.",
  "level": 43,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "BAGON",
    "moves": [
     "DRAGON_BREATH",
     "AERIAL_ACE",
     "DRAGON_DANCE",
     "HEADBUTT"
    ]
   },
   {
    "species": "SHELGON",
    "moves": [
     "DRAGON_CLAW",
     "BRICK_BREAK",
     "DRAGON_DANCE",
     "THRASH"
    ]
   },
   {
    "species": "SALAMENCE",
    "moves": [
     "DRAGON_CLAW",
     "AERIAL_ACE",
     "EARTHQUAKE",
     "DRAGON_DANCE"
    ]
   }
  ]
 },
 {
  "id": "beldum",
  "role": "Heavy Hitter",
  "blurb": "The Iron Leg Pokémon. Ability: Clear Body.",
  "level": 43,
  "evoRate": 1.5,
  "tags": [
   "hoenn"
  ],
  "stages": [
   {
    "species": "BELDUM",
    "moves": [
     "TAKE_DOWN"
    ]
   },
   {
    "species": "METANG",
    "moves": [
     "METAL_CLAW",
     "PSYCHIC",
     "BRICK_BREAK",
     "AGILITY"
    ]
   },
   {
    "species": "METAGROSS",
    "moves": [
     "METEOR_MASH",
     "PSYCHIC",
     "EARTHQUAKE",
     "AGILITY"
    ]
   }
  ]
 },
 {
  "id": "regirock",
  "role": "Legendary",
  "blurb": "The Rock Peak Pokémon. Ability: Clear Body.",
  "level": 41,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "REGIROCK",
    "moves": [
     "ROCK_SLIDE",
     "SUPERPOWER",
     "THUNDER_WAVE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "regice",
  "role": "Legendary",
  "blurb": "The Iceberg Pokémon. Ability: Clear Body.",
  "level": 41,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "REGICE",
    "moves": [
     "ICE_BEAM",
     "THUNDERBOLT",
     "THUNDER_WAVE",
     "BLIZZARD"
    ]
   }
  ]
 },
 {
  "id": "registeel",
  "role": "Legendary",
  "blurb": "The Iron Pokémon. Ability: Clear Body.",
  "level": 41,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "REGISTEEL",
    "moves": [
     "METAL_CLAW",
     "SUPERPOWER",
     "THUNDER_WAVE",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "latias",
  "role": "Legendary",
  "blurb": "The Eon Pokémon. Ability: Levitate.",
  "level": 39,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "LATIAS",
    "moves": [
     "DRAGON_CLAW",
     "PSYCHIC",
     "ICE_BEAM",
     "RECOVER"
    ]
   }
  ]
 },
 {
  "id": "latios",
  "role": "Legendary",
  "blurb": "The Eon Pokémon. Ability: Levitate.",
  "level": 39,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "LATIOS",
    "moves": [
     "DRAGON_CLAW",
     "PSYCHIC",
     "ICE_BEAM",
     "RECOVER"
    ]
   }
  ]
 },
 {
  "id": "kyogre",
  "role": "Legendary",
  "blurb": "The Sea Basin Pokémon. Ability: Drizzle.",
  "level": 33,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "KYOGRE",
    "moves": [
     "WATER_SPOUT",
     "ICE_BEAM",
     "CALM_MIND",
     "HYDRO_PUMP"
    ]
   }
  ]
 },
 {
  "id": "groudon",
  "role": "Legendary",
  "blurb": "The Continent Pokémon. Ability: Drought.",
  "level": 33,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "GROUDON",
    "moves": [
     "EARTHQUAKE",
     "BRICK_BREAK",
     "BULK_UP",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "rayquaza",
  "role": "Legendary",
  "blurb": "The Sky High Pokémon. Ability: Air Lock.",
  "level": 33,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "RAYQUAZA",
    "moves": [
     "OUTRAGE",
     "AERIAL_ACE",
     "EARTHQUAKE",
     "DRAGON_DANCE"
    ]
   }
  ]
 },
 {
  "id": "jirachi",
  "role": "Legendary",
  "blurb": "The Wish Pokémon. Ability: Serene Grace.",
  "level": 39,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "JIRACHI",
    "moves": [
     "PSYCHIC",
     "THUNDERBOLT",
     "WISH",
     "DOUBLE_EDGE"
    ]
   }
  ]
 },
 {
  "id": "deoxys",
  "role": "Legendary",
  "blurb": "The Dna Pokémon. Ability: Pressure.",
  "level": 39,
  "tags": [
   "hoenn",
   "legendary"
  ],
  "stages": [
   {
    "species": "DEOXYS",
    "moves": [
     "PSYCHO_BOOST",
     "ICE_BEAM",
     "THUNDER_WAVE",
     "PSYCHIC"
    ]
   }
  ]
 }
];
