/**
 * Playable roster. Each line lists its evolution stages; every stage has a curated 4-move set.
 * All moves are legal for that species in FireRed (level-up / TM / HM / tutor / egg, or inherited
 * from a pre-evolution) — enforced by `yarn roster:validate`.
 *
 * Design rule: stage 1 moves ~35-70 power, stage 2 ~60-95, final stage gets its signature nukes.
 * `level` is the per-line balance knob (FireRed itself balances trainers with levels);
 * it's tuned with `yarn sim`.
 */
import levelsJson from './levels.json';
import { GENERATED } from './roster.generated';

export interface RosterStage {
  species: string; // key into SPECIES
  moves: string[]; // 1-4 moves (Magikarp only has 3 legal moves in FireRed)
}

export interface RosterLine {
  id: string;
  /** generated lines carry extra tags for filtering in team select */
  tags?: string[];
  role: string; // short playstyle tag shown in team select
  blurb: string; // one-line strategy hint
  level: number;
  /** evolution-energy gain multiplier (default 1). Magikarp needs to become Gyarados quickly. */
  evoRate?: number;
  stages: RosterStage[];
}

/** Hand-curated lines (phase 1 + 2 + local session 1). Everything else is generated by tools/gen-roster.ts. */
export const CURATED: RosterLine[] = [
  {
    id: 'bulbasaur',
    role: 'Controller',
    blurb: 'Seeds, sleep and drain wear foes down; Frenzy Plant finishes them.',
    level: 43,
    stages: [
      { species: 'BULBASAUR', moves: ['RAZOR_LEAF', 'TACKLE', 'LEECH_SEED', 'POISON_POWDER'] },
      { species: 'IVYSAUR', moves: ['RAZOR_LEAF', 'SLUDGE_BOMB', 'LEECH_SEED', 'SLEEP_POWDER'] },
      { species: 'VENUSAUR', moves: ['FRENZY_PLANT', 'GIGA_DRAIN', 'SLUDGE_BOMB', 'SLEEP_POWDER'] },
    ],
  },
  {
    id: 'charmander',
    role: 'Special Sweeper',
    blurb: 'Weak start, explosive finish. Blaze boosts fire moves at low HP.',
    level: 53,
    stages: [
      { species: 'CHARMANDER', moves: ['EMBER', 'METAL_CLAW', 'SCRATCH', 'SMOKESCREEN'] },
      { species: 'CHARMELEON', moves: ['FLAMETHROWER', 'SLASH', 'DRAGON_RAGE', 'SCARY_FACE'] },
      { species: 'CHARIZARD', moves: ['BLAST_BURN', 'FLAMETHROWER', 'DRAGON_CLAW', 'WING_ATTACK'] },
    ],
  },
  {
    id: 'squirtle',
    role: 'Tank',
    blurb: 'Hard to break. Protect and Withdraw buy time for Hydro Cannon.',
    level: 53,
    stages: [
      { species: 'SQUIRTLE', moves: ['WATER_GUN', 'BITE', 'TACKLE', 'WITHDRAW'] },
      { species: 'WARTORTLE', moves: ['WATER_PULSE', 'BITE', 'SKULL_BASH', 'PROTECT'] },
      { species: 'BLASTOISE', moves: ['HYDRO_CANNON', 'SURF', 'ICE_BEAM', 'PROTECT'] },
    ],
  },
  {
    id: 'pidgey',
    role: 'Speedster',
    blurb: 'Fast gauge, never-miss Aerial Ace and Agility to act even faster.',
    level: 61,
    stages: [
      { species: 'PIDGEY', moves: ['GUST', 'QUICK_ATTACK', 'TACKLE', 'SAND_ATTACK'] },
      { species: 'PIDGEOTTO', moves: ['WING_ATTACK', 'QUICK_ATTACK', 'STEEL_WING', 'FEATHER_DANCE'] },
      { species: 'PIDGEOT', moves: ['AERIAL_ACE', 'DOUBLE_EDGE', 'STEEL_WING', 'AGILITY'] },
    ],
  },
  {
    id: 'pikachu',
    role: 'Striker',
    blurb: 'Only one evolution, but it comes fast. Paralyze, then Thunder.',
    level: 47,
    stages: [
      { species: 'PIKACHU', moves: ['THUNDERBOLT', 'QUICK_ATTACK', 'IRON_TAIL', 'THUNDER_WAVE'] },
      { species: 'RAICHU', moves: ['THUNDERBOLT', 'THUNDER', 'BRICK_BREAK', 'QUICK_ATTACK'] },
    ],
  },
  {
    id: 'abra',
    role: 'Glass Cannon',
    blurb: 'Enormous Sp. Atk, paper-thin. Elemental punches are special in Gen 3!',
    level: 42,
    stages: [
      { species: 'ABRA', moves: ['PSYCHIC', 'THUNDER_PUNCH', 'THUNDER_WAVE', 'REFLECT'] },
      { species: 'KADABRA', moves: ['PSYCHIC', 'ICE_PUNCH', 'RECOVER', 'REFLECT'] },
      { species: 'ALAKAZAM', moves: ['PSYCHIC', 'FIRE_PUNCH', 'CALM_MIND', 'RECOVER'] },
    ],
  },
  {
    id: 'machop',
    role: 'Bruiser',
    blurb: 'Guts turns status into power. Dynamic Punch always confuses.',
    level: 48,
    stages: [
      { species: 'MACHOP', moves: ['KARATE_CHOP', 'ROCK_TOMB', 'LOW_KICK', 'BULK_UP'] },
      { species: 'MACHOKE', moves: ['VITAL_THROW', 'ROCK_SLIDE', 'BRICK_BREAK', 'BULK_UP'] },
      { species: 'MACHAMP', moves: ['CROSS_CHOP', 'DYNAMIC_PUNCH', 'ROCK_SLIDE', 'EARTHQUAKE'] },
    ],
  },
  {
    id: 'geodude',
    role: 'Wall Breaker',
    blurb: 'Rock Head means no recoil. Golem can Explode as a last resort.',
    level: 60,
    stages: [
      { species: 'GEODUDE', moves: ['ROCK_THROW', 'DIG', 'ROCK_SMASH', 'DEFENSE_CURL'] },
      { species: 'GRAVELER', moves: ['ROCK_BLAST', 'DIG', 'BRICK_BREAK', 'DEFENSE_CURL'] },
      { species: 'GOLEM', moves: ['EARTHQUAKE', 'ROCK_SLIDE', 'DOUBLE_EDGE', 'EXPLOSION'] },
    ],
  },
  {
    id: 'seel',
    role: 'Support Tank',
    blurb: 'Thick Fat shrugs off fire & ice. Rest to reset.',
    level: 48,
    stages: [
      { species: 'SEEL', moves: ['AURORA_BEAM', 'WATER_PULSE', 'HEADBUTT', 'REST'] },
      { species: 'DEWGONG', moves: ['ICE_BEAM', 'SURF', 'HEADBUTT', 'REST'] },
    ],
  },
  {
    id: 'gastly',
    role: 'Trickster',
    blurb: 'Levitate + Normal/Fighting immunity. Hypnosis into Dream Eater.',
    level: 49,
    stages: [
      { species: 'GASTLY', moves: ['NIGHT_SHADE', 'LICK', 'HYPNOSIS', 'CONFUSE_RAY'] },
      { species: 'HAUNTER', moves: ['NIGHT_SHADE', 'DREAM_EATER', 'HYPNOSIS', 'CONFUSE_RAY'] },
      { species: 'GENGAR', moves: ['SHADOW_BALL', 'THUNDERBOLT', 'DREAM_EATER', 'HYPNOSIS'] },
    ],
  },
  {
    id: 'scyther',
    role: 'Duelist',
    blurb: 'Strong from turn one. Evolving trades speed for Steel armor.',
    level: 42,
    stages: [
      { species: 'SCYTHER', moves: ['SILVER_WIND', 'WING_ATTACK', 'QUICK_ATTACK', 'SWORDS_DANCE'] },
      { species: 'SCIZOR', moves: ['STEEL_WING', 'SILVER_WIND', 'QUICK_ATTACK', 'SWORDS_DANCE'] },
    ],
  },
  {
    id: 'dratini',
    role: 'Late Bloomer',
    blurb: 'Two evolutions to Dragonite — the strongest finisher in the roster.',
    level: 47,
    stages: [
      { species: 'DRATINI', moves: ['TWISTER', 'DRAGON_RAGE', 'SLAM', 'THUNDER_WAVE'] },
      { species: 'DRAGONAIR', moves: ['DRAGON_BREATH', 'ICE_BEAM', 'THUNDER_WAVE', 'AGILITY'] },
      { species: 'DRAGONITE', moves: ['OUTRAGE', 'HYPER_BEAM', 'WING_ATTACK', 'DRAGON_DANCE'] },
    ],
  },
  {
    id: 'houndour',
    role: 'Hunter',
    blurb: 'Fire + Dark coverage. Burns cripple physical attackers.',
    level: 50,
    stages: [
      { species: 'HOUNDOUR', moves: ['EMBER', 'BITE', 'SMOG', 'HOWL'] },
      { species: 'HOUNDOOM', moves: ['FLAMETHROWER', 'CRUNCH', 'SOLAR_BEAM', 'WILL_O_WISP'] },
    ],
  },
  {
    id: 'magikarp',
    role: 'Underdog',
    blurb: 'Useless... until it isn\'t. Evolves very fast into a rampaging Gyarados.',
    level: 49,
    evoRate: 2.4,
    stages: [
      { species: 'MAGIKARP', moves: ['SPLASH', 'TACKLE', 'FLAIL'] },
      { species: 'GYARADOS', moves: ['HYDRO_PUMP', 'THRASH', 'EARTHQUAKE', 'DRAGON_DANCE'] },
    ],
  },
  {
    id: 'nidoran',
    role: 'Coverage King',
    blurb: 'Poison Point punishes contact. Nidoking hits almost everything super-effectively.',
    level: 54,
    stages: [
      { species: 'NIDORAN_M', moves: ['HORN_ATTACK', 'DOUBLE_KICK', 'POISON_STING', 'FOCUS_ENERGY'] },
      { species: 'NIDORINO', moves: ['SLUDGE_BOMB', 'HORN_ATTACK', 'DOUBLE_KICK', 'DIG'] },
      { species: 'NIDOKING', moves: ['EARTHQUAKE', 'MEGAHORN', 'SLUDGE_BOMB', 'THUNDERBOLT'] },
    ],
  },
  {
    id: 'oddish',
    role: 'Status Spreader',
    blurb: 'Stun, poison, sleep — then Petal Dance through the chaos.',
    level: 50,
    stages: [
      { species: 'ODDISH', moves: ['ABSORB', 'ACID', 'STUN_SPORE', 'POISON_POWDER'] },
      { species: 'GLOOM', moves: ['GIGA_DRAIN', 'ACID', 'SLEEP_POWDER', 'MOONLIGHT'] },
      { species: 'VILEPLUME', moves: ['PETAL_DANCE', 'SLUDGE_BOMB', 'STUN_SPORE', 'MOONLIGHT'] },
    ],
  },
  {
    id: 'poliwag',
    role: 'Gambler',
    blurb: 'Water Absorb eats water moves. Belly Drum: half your HP for maximum Attack.',
    level: 50,
    stages: [
      { species: 'POLIWAG', moves: ['WATER_GUN', 'DOUBLE_SLAP', 'HYPNOSIS', 'BUBBLE'] },
      { species: 'POLIWHIRL', moves: ['WATER_PULSE', 'BODY_SLAM', 'HYPNOSIS', 'BELLY_DRUM'] },
      { species: 'POLIWRATH', moves: ['SURF', 'BRICK_BREAK', 'HYPNOSIS', 'BELLY_DRUM'] },
    ],
  },
  {
    id: 'onix',
    role: 'Iron Wall',
    blurb: 'Colossal Defense. Evolving into Steelix adds Steel armor and real power.',
    level: 53,
    stages: [
      { species: 'ONIX', moves: ['ROCK_THROW', 'DRAGON_BREATH', 'SCREECH', 'HARDEN'] },
      { species: 'STEELIX', moves: ['IRON_TAIL', 'EARTHQUAKE', 'CRUNCH', 'ROCK_SLIDE'] },
    ],
  },
  {
    id: 'larvitar',
    role: 'Pseudo-Legend',
    blurb: 'A slow start, then Tyranitar: the heaviest hitter in Kanto and Johto — its Sand Stream brews a sandstorm.',
    level: 52,
    stages: [
      { species: 'LARVITAR', moves: ['BITE', 'ROCK_SLIDE', 'DIG', 'SCREECH'] },
      { species: 'PUPITAR', moves: ['ROCK_SLIDE', 'CRUNCH', 'DIG', 'SCARY_FACE'] },
      { species: 'TYRANITAR', moves: ['EARTHQUAKE', 'ROCK_SLIDE', 'CRUNCH', 'DRAGON_DANCE'] },
    ],
  },

  // ---- curated in local session 1 (FireRed-legal sets, weather teams) ----
  {
    id: 'chikorita',
    tags: ['johto'],
    role: 'Sun Support',
    blurb: 'Reflect and Synthesis keep it standing; Meganium calls the sun for an instant Solar Beam.',
    level: 50,
    evoRate: 1.88,
    stages: [
      { species: 'CHIKORITA', moves: ['RAZOR_LEAF', 'TACKLE', 'REFLECT', 'POISON_POWDER'] },
      { species: 'BAYLEEF', moves: ['GIGA_DRAIN', 'BODY_SLAM', 'REFLECT', 'SYNTHESIS'] },
      { species: 'MEGANIUM', moves: ['SOLAR_BEAM', 'BODY_SLAM', 'SUNNY_DAY', 'SYNTHESIS'] },
    ],
  },
  {
    id: 'cyndaquil',
    tags: ['johto'],
    role: 'Speedster',
    blurb: 'Quick Attack pokes, Reversal bites back at low HP; Typhlosion torches with Flamethrower and Overheat.',
    level: 49,
    evoRate: 2.14,
    stages: [
      { species: 'CYNDAQUIL', moves: ['FLAME_WHEEL', 'QUICK_ATTACK', 'SMOKESCREEN', 'REVERSAL'] },
      { species: 'QUILAVA', moves: ['FLAMETHROWER', 'QUICK_ATTACK', 'DIG', 'SMOKESCREEN'] },
      { species: 'TYPHLOSION', moves: ['FLAMETHROWER', 'OVERHEAT', 'EARTHQUAKE', 'QUICK_ATTACK'] },
    ],
  },
  {
    id: 'totodile',
    tags: ['johto'],
    role: 'Jaws',
    blurb: 'Bite and Crunch never let go; Feraligatr calls the rain for a boosted Hydro Pump.',
    level: 49,
    evoRate: 1.67,
    stages: [
      { species: 'TOTODILE', moves: ['WATER_GUN', 'BITE', 'RAGE', 'SCARY_FACE'] },
      { species: 'CROCONAW', moves: ['WATERFALL', 'CRUNCH', 'SLASH', 'SCREECH'] },
      { species: 'FERALIGATR', moves: ['HYDRO_PUMP', 'CRUNCH', 'EARTHQUAKE', 'RAIN_DANCE'] },
    ],
  },
  {
    id: 'treecko',
    tags: ['hoenn'],
    role: 'Blade Master',
    blurb: 'Leech Seed wears foes down; Sceptile slices with a high-crit Leaf Blade and Dragon Claw.',
    level: 49,
    evoRate: 1.88,
    stages: [
      { species: 'TREECKO', moves: ['MEGA_DRAIN', 'QUICK_ATTACK', 'PURSUIT', 'LEECH_SEED'] },
      { species: 'GROVYLE', moves: ['LEAF_BLADE', 'DRAGON_BREATH', 'QUICK_ATTACK', 'AGILITY'] },
      { species: 'SCEPTILE', moves: ['LEAF_BLADE', 'DRAGON_CLAW', 'EARTHQUAKE', 'LEECH_SEED'] },
    ],
  },
  {
    id: 'torchic',
    tags: ['hoenn'],
    role: 'Brawler',
    blurb: 'Bulk Up, then Blaze Kick and Sky Uppercut: Blaziken is a fire-fighting martial artist.',
    level: 49,
    evoRate: 1.88,
    stages: [
      { species: 'TORCHIC', moves: ['EMBER', 'PECK', 'QUICK_ATTACK', 'FOCUS_ENERGY'] },
      { species: 'COMBUSKEN', moves: ['FLAMETHROWER', 'DOUBLE_KICK', 'BULK_UP', 'ROCK_TOMB'] },
      { species: 'BLAZIKEN', moves: ['BLAZE_KICK', 'SKY_UPPERCUT', 'EARTHQUAKE', 'BULK_UP'] },
    ],
  },
  {
    id: 'mudkip',
    tags: ['hoenn'],
    role: 'Mud Tank',
    blurb: 'Tough and patient: Muddy Water and Earthquake, while Mirror Coat punishes special hits.',
    level: 49,
    evoRate: 1.88,
    stages: [
      { species: 'MUDKIP', moves: ['WATER_GUN', 'MUD_SLAP', 'STOMP', 'PROTECT'] },
      { species: 'MARSHTOMP', moves: ['WATER_PULSE', 'MUD_SHOT', 'ROCK_SLIDE', 'PROTECT'] },
      { species: 'SWAMPERT', moves: ['MUDDY_WATER', 'EARTHQUAKE', 'ICE_BEAM', 'MIRROR_COAT'] },
    ],
  },
  {
    id: 'bagon',
    tags: ['hoenn'],
    role: 'Dreamer',
    blurb: 'Shelgon turtles up; Salamence finally spreads its wings and sweeps after a Dragon Dance.',
    level: 43,
    stages: [
      { species: 'BAGON', moves: ['HEADBUTT', 'DRAGON_RAGE', 'BITE', 'FOCUS_ENERGY'] },
      { species: 'SHELGON', moves: ['DRAGON_BREATH', 'BODY_SLAM', 'PROTECT', 'DRAGON_DANCE'] },
      { species: 'SALAMENCE', moves: ['DRAGON_CLAW', 'FLY', 'EARTHQUAKE', 'DRAGON_DANCE'] },
    ],
  },
  {
    id: 'beldum',
    tags: ['hoenn'],
    role: 'Iron Mind',
    blurb: 'Beldum only knows Take Down — hang on until Metagross drops Meteor Mash.',
    level: 43,
    evoRate: 1.5,
    stages: [
      { species: 'BELDUM', moves: ['TAKE_DOWN'] },
      { species: 'METANG', moves: ['METAL_CLAW', 'PSYCHIC', 'ROCK_SLIDE', 'IRON_DEFENSE'] },
      { species: 'METAGROSS', moves: ['METEOR_MASH', 'PSYCHIC', 'EARTHQUAKE', 'AGILITY'] },
    ],
  },
  {
    id: 'ralts',
    tags: ['hoenn'],
    role: 'Calm Mind',
    blurb: 'Calm Mind, then Psychic and Thunderbolt; Will-O-Wisp cripples physical attackers.',
    level: 50,
    evoRate: 1.5,
    stages: [
      { species: 'RALTS', moves: ['CONFUSION', 'SHOCK_WAVE', 'THUNDER_WAVE', 'CALM_MIND'] },
      { species: 'KIRLIA', moves: ['PSYCHIC', 'MAGICAL_LEAF', 'SHOCK_WAVE', 'CALM_MIND'] },
      { species: 'GARDEVOIR', moves: ['PSYCHIC', 'THUNDERBOLT', 'CALM_MIND', 'WILL_O_WISP'] },
    ],
  },
  {
    id: 'aron',
    tags: ['hoenn'],
    role: 'Sand Armor',
    blurb: 'Steel/Rock shrugs off sand: Aggron whips up a Sandstorm and outlasts everything.',
    level: 49,
    evoRate: 0.94,
    stages: [
      { species: 'ARON', moves: ['METAL_CLAW', 'ROCK_TOMB', 'HEADBUTT', 'IRON_DEFENSE'] },
      { species: 'LAIRON', moves: ['IRON_TAIL', 'ROCK_SLIDE', 'TAKE_DOWN', 'PROTECT'] },
      { species: 'AGGRON', moves: ['IRON_TAIL', 'ROCK_SLIDE', 'EARTHQUAKE', 'SANDSTORM'] },
    ],
  },
  {
    id: 'lapras',
    tags: ['kanto'],
    role: 'Ferry',
    blurb: 'FireRed\'s gentle giant: Surf, Ice Beam, Thunderbolt and a lullaby.',
    level: 45,
    stages: [
      { species: 'LAPRAS', moves: ['SURF', 'ICE_BEAM', 'THUNDERBOLT', 'SING'] },
    ],
  },
  {
    id: 'snorlax',
    tags: ['kanto'],
    role: 'Sleeping Giant',
    blurb: 'Belly Drum for maximum Attack, Body Slam through everything, Rest when tired.',
    level: 44,
    stages: [
      { species: 'SNORLAX', moves: ['BODY_SLAM', 'EARTHQUAKE', 'BELLY_DRUM', 'REST'] },
    ],
  },
  {
    id: 'eevee-espeon',
    tags: ['kanto', 'branch'],
    role: 'Sun Psychic',
    blurb: 'Calm Mind and Psychic; Morning Sun heals even more in harsh sunlight.',
    level: 46,
    evoRate: 1.1,
    stages: [
      { species: 'EEVEE', moves: ['QUICK_ATTACK', 'BITE', 'CHARM', 'WISH'] },
      { species: 'ESPEON', moves: ['PSYCHIC', 'HIDDEN_POWER', 'CALM_MIND', 'MORNING_SUN'] },
    ],
  },
  {
    id: 'eevee-umbreon',
    tags: ['kanto', 'branch'],
    role: 'Night Wall',
    blurb: 'Toxic, Confuse Ray and Moonlight — a dark wall that wins the long game.',
    level: 46,
    evoRate: 1.1,
    stages: [
      { species: 'EEVEE', moves: ['QUICK_ATTACK', 'BITE', 'CHARM', 'WISH'] },
      { species: 'UMBREON', moves: ['FAINT_ATTACK', 'TOXIC', 'CONFUSE_RAY', 'MOONLIGHT'] },
    ],
  },
  {
    id: 'eevee-vaporeon',
    tags: ['kanto', 'branch'],
    role: 'Rain Tank',
    blurb: 'Rain Dance boosts Surf; Wish keeps its huge HP pool topped up.',
    level: 46,
    evoRate: 1.1,
    stages: [
      { species: 'EEVEE', moves: ['QUICK_ATTACK', 'BITE', 'CHARM', 'WISH'] },
      { species: 'VAPOREON', moves: ['SURF', 'ICE_BEAM', 'RAIN_DANCE', 'WISH'] },
    ],
  },
  {
    id: 'eevee-jolteon',
    tags: ['kanto', 'branch'],
    role: 'Lightning',
    blurb: 'Blazing Speed with Thunderbolt and Pin Missile; Thunder Wave slows the chase.',
    level: 46,
    evoRate: 1.1,
    stages: [
      { species: 'EEVEE', moves: ['QUICK_ATTACK', 'BITE', 'CHARM', 'WISH'] },
      { species: 'JOLTEON', moves: ['THUNDERBOLT', 'HIDDEN_POWER', 'PIN_MISSILE', 'THUNDER_WAVE'] },
    ],
  },
  {
    id: 'eevee-flareon',
    tags: ['kanto', 'branch'],
    role: 'Sun Blaze',
    blurb: 'Sunny Day powers up Flamethrower; its huge Attack fuels Double-Edge and Shadow Ball.',
    level: 46,
    evoRate: 1.1,
    stages: [
      { species: 'EEVEE', moves: ['QUICK_ATTACK', 'BITE', 'CHARM', 'WISH'] },
      { species: 'FLAREON', moves: ['FLAMETHROWER', 'DOUBLE_EDGE', 'SHADOW_BALL', 'SUNNY_DAY'] },
    ],
  },
  {
    id: 'lugia',
    tags: ['johto', 'legendary'],
    role: 'Diving Guardian',
    blurb: 'Aeroblast, Psychic and Ice Beam, with Recover to hold the skies.',
    level: 33,
    stages: [
      { species: 'LUGIA', moves: ['AEROBLAST', 'PSYCHIC', 'ICE_BEAM', 'RECOVER'] },
    ],
  },
  {
    id: 'ho-oh',
    tags: ['johto', 'legendary'],
    role: 'Rainbow Phoenix',
    blurb: 'Sunny Day powers up Sacred Fire; Earthquake answers Rock types.',
    level: 33,
    stages: [
      { species: 'HO_OH', moves: ['SACRED_FIRE', 'EARTHQUAKE', 'SUNNY_DAY', 'RECOVER'] },
    ],
  },
  {
    id: 'mewtwo',
    tags: ['kanto', 'legendary'],
    role: 'Genetic',
    blurb: 'Psychic with Thunderbolt and Ice Beam coverage — and Recover.',
    level: 33,
    stages: [
      { species: 'MEWTWO', moves: ['PSYCHIC', 'THUNDERBOLT', 'ICE_BEAM', 'RECOVER'] },
    ],
  },
  {
    id: 'groudon',
    tags: ['hoenn', 'legendary'],
    role: 'Drought',
    blurb: 'Drought brings harsh sunlight on entry: instant Solar Beam and a sun-boosted Eruption.',
    level: 33,
    stages: [
      { species: 'GROUDON', moves: ['EARTHQUAKE', 'ERUPTION', 'SOLAR_BEAM', 'BULK_UP'] },
    ],
  },
  {
    id: 'kyogre',
    tags: ['hoenn', 'legendary'],
    role: 'Drizzle',
    blurb: 'Drizzle brings rain on entry: Water Spout hits like a tsunami and Thunder never misses.',
    level: 33,
    stages: [
      { species: 'KYOGRE', moves: ['WATER_SPOUT', 'THUNDER', 'ICE_BEAM', 'CALM_MIND'] },
    ],
  },
  {
    id: 'rayquaza',
    tags: ['hoenn', 'legendary'],
    role: 'Air Lock',
    blurb: 'Air Lock cancels all weather; Dragon Dance, then Outrage and Extreme Speed.',
    level: 33,
    stages: [
      { species: 'RAYQUAZA', moves: ['OUTRAGE', 'EXTREME_SPEED', 'EARTHQUAKE', 'DRAGON_DANCE'] },
    ],
  },
  {
    id: 'latias',
    tags: ['hoenn', 'legendary'],
    role: 'Mist Ball',
    blurb: 'Calm Mind and Recover; Mist Ball lowers the foe\'s Sp. Atk.',
    level: 39,
    stages: [
      { species: 'LATIAS', moves: ['MIST_BALL', 'DRAGON_CLAW', 'CALM_MIND', 'RECOVER'] },
    ],
  },
  {
    id: 'latios',
    tags: ['hoenn', 'legendary'],
    role: 'Luster Purge',
    blurb: 'The attacking twin: Luster Purge, Dragon Claw and Thunderbolt.',
    level: 39,
    stages: [
      { species: 'LATIOS', moves: ['LUSTER_PURGE', 'DRAGON_CLAW', 'THUNDERBOLT', 'RECOVER'] },
    ],
  },
  {
    id: 'deoxys',
    tags: ['hoenn', 'legendary'],
    role: 'Attack Forme',
    blurb: 'Psycho Boost first, then keep hitting with physical Shadow Ball and Brick Break.',
    level: 39,
    stages: [
      { species: 'DEOXYS', moves: ['PSYCHO_BOOST', 'SHADOW_BALL', 'BRICK_BREAK', 'ICE_BEAM'] },
    ],
  },
  {
    id: 'castform',
    tags: ['hoenn'],
    role: 'Forecast',
    blurb: 'Changes type with the weather; Weather Ball becomes a 100-power Fire or Water blast.',
    level: 54,
    stages: [
      { species: 'CASTFORM', moves: ['WEATHER_BALL', 'SUNNY_DAY', 'RAIN_DANCE', 'SOLAR_BEAM'] },
    ],
  },
  {
    id: 'lotad',
    tags: ['hoenn'],
    role: 'Rain Dancer',
    blurb: 'Swift Swim doubles its Speed in rain — Ludicolo dances through with Hydro Pump and Giga Drain.',
    level: 53,
    evoRate: 2.14,
    stages: [
      { species: 'LOTAD', moves: ['WATER_PULSE', 'MEGA_DRAIN', 'LEECH_SEED', 'RAIN_DANCE'] },
      { species: 'LOMBRE', moves: ['SURF', 'GIGA_DRAIN', 'FAKE_OUT', 'RAIN_DANCE'] },
      { species: 'LUDICOLO', moves: ['HYDRO_PUMP', 'GIGA_DRAIN', 'ICE_BEAM', 'RAIN_DANCE'] },
    ],
  },
  {
    id: 'horsea',
    tags: ['kanto'],
    role: 'Rain Dragon',
    blurb: 'Kingdra calls the rain for Swift Swim speed and boosted Hydro Pumps.',
    level: 48,
    evoRate: 0.94,
    stages: [
      { species: 'HORSEA', moves: ['WATER_PULSE', 'TWISTER', 'SMOKESCREEN', 'RAIN_DANCE'] },
      { species: 'SEADRA', moves: ['SURF', 'DRAGON_BREATH', 'ICE_BEAM', 'AGILITY'] },
      { species: 'KINGDRA', moves: ['HYDRO_PUMP', 'DRAGON_BREATH', 'ICE_BEAM', 'RAIN_DANCE'] },
    ],
  },
  {
    id: 'exeggcute',
    tags: ['kanto'],
    role: 'Sun Sweeper',
    blurb: 'Chlorophyll + Sunny Day: double Speed and an instant 120-power Solar Beam.',
    level: 47,
    evoRate: 1.1,
    stages: [
      { species: 'EXEGGCUTE', moves: ['CONFUSION', 'GIGA_DRAIN', 'SLEEP_POWDER', 'SUNNY_DAY'] },
      { species: 'EXEGGUTOR', moves: ['SOLAR_BEAM', 'PSYCHIC', 'SUNNY_DAY', 'SLEEP_POWDER'] },
    ],
  },
  {
    id: 'bellsprout',
    tags: ['kanto'],
    role: 'Sun Striker',
    blurb: 'Chlorophyll speed in the sun, Sleep Powder, then Solar Beam or Sludge Bomb.',
    level: 53,
    evoRate: 1.43,
    stages: [
      { species: 'BELLSPROUT', moves: ['RAZOR_LEAF', 'ACID', 'SLEEP_POWDER', 'SUNNY_DAY'] },
      { species: 'WEEPINBELL', moves: ['GIGA_DRAIN', 'SLUDGE_BOMB', 'STUN_SPORE', 'SUNNY_DAY'] },
      { species: 'VICTREEBEL', moves: ['SOLAR_BEAM', 'SLUDGE_BOMB', 'SUNNY_DAY', 'SLEEP_POWDER'] },
    ],
  },
];

/** Tuned levels (tools/tune-levels.ts) override the defaults above. */
const levelOverrides = levelsJson as Record<string, number>;

export const ROSTER: RosterLine[] = [...CURATED, ...GENERATED].map((l) => ({ ...l, level: levelOverrides[l.id] ?? l.level }));

const byId = new Map(ROSTER.map((l) => [l.id, l]));

export function getLine(id: string): RosterLine {
  const l = byId.get(id);
  if (!l) throw new Error(`Unknown roster line: ${id}`);
  return l;
}
